packages:
  - "."

# pnpm 10 compatibility
onlyBuiltDependencies:
  - '@firebase/util'
  - '@google/genai'
  - '@prisma/client'
  - '@prisma/engines'
  - core-js
  - esbuild
  - prisma
  - protobufjs

# pnpm 11 compatibility
allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  '@prisma/client': true
  '@prisma/engines': true
  core-js: true
  esbuild: true
  prisma: true
  protobufjs: true
