import { Product, CategoryKey } from '../../../types';

/**
 * Delta Stars Sovereign Data Engine v63.0
 * قاعدة البيانات الشاملة والمعالجة (240 صنفاً فريداً)
 */

const fixDriveLink = (idOrUrl: string) => {
    if (!idOrUrl) return "/official_logo.png?v=2026";
    
    if (idOrUrl.startsWith('http')) return idOrUrl;

    let cleanId = idOrUrl;
    if (idOrUrl.includes('id=')) {
        const parts = idOrUrl.split('id=');
        cleanId = parts[parts.length - 1];
    } else if (idOrUrl.includes('/d/')) {
        const parts = idOrUrl.split('/d/');
        cleanId = parts[1].split('/')[0];
    }

    cleanId = cleanId.split('/view')[0].split('?')[0].split('&')[0];
    
    return `https://lh3.googleusercontent.com/d/${cleanId}`;
};

const mapUnitArToEn = (unitAr: string): string => {
    if (unitAr.includes('كيلو')) return 'kg';
    if (unitAr.includes('حبة')) return 'pc';
    if (unitAr.includes('عبوة')) return 'PK';
    if (unitAr.includes('كرتون')) return 'Ctn';
    if (unitAr.includes('طبق')) return 'Box';
    if (unitAr.includes('سلة')) return 'Basket';
    return 'unit';
};

const mapCategory = (catAr: string, nameAr: string): CategoryKey => {
  const name = nameAr.toLowerCase();
  const cat = catAr.toLowerCase();

  // 1. If it's in the الورقيات والأعشاب category, it's herbs
  if (cat.includes('الورقيات') || cat.includes('أعشاب')) {
    return 'herbs';
  }

  // 2. If it's in الفواكه category, it's fruits
  if (cat.includes('الفواكه') || cat.includes('فواكه')) {
    return 'fruits';
  }

  // 3. If it's in الخضروات الأساسية والمحلية or خضروات
  if (cat.includes('الأساسية والمحلية') || cat === 'خضروات') {
    return 'vegetables';
  }

  // 4. If it's in الخضروات المستوردة والخاصة
  if (cat.includes('المستوردة') || cat.includes('مستورد')) {
    if (name.includes('فطر') || name.includes('مشروم')) {
      return 'seasonal';
    }
    if (name.includes('أفوكادو')) {
      return 'fruits';
    }
    return 'vegetables';
  }

  // 5. If it's in the mixed category "أصناف القصيم والتمور ومنوعة"
  if (cat.includes('القصيم') || cat.includes('تمور') || cat.includes('منوعة')) {
    // A. Check for dates/تمور first
    if (
      name.includes('تمر') ||
      name.includes('سكري') ||
      name.includes('مجدول') ||
      name.includes('صقعي') || 
      name.includes('مبروم') ||
      name.includes('صفاوي') ||
      name.includes('عنبر') ||
      name.includes('عجوة') || 
      name.includes('رطب') ||
      name.includes('خلاص')
    ) {
      if (name.includes('تفاح')) {
        return 'fruits';
      }
      return 'dates';
    }

    // B. Check for Packages/سلال ومغلفات
    if (name.includes('سلة') || name.includes('صندوق') || name.includes('عبوة') || name.includes('مغلف')) {
      return 'packages';
    }

    // C. Check for Flowers / زهور
    if (name.includes('زهور') || (name.includes('ورد') && !name.includes('مستورد'))) {
      return 'flowers';
    }

    // D. Check for Fruits
    if (
      name.includes('توت') ||
      name.includes('جوز الهند') ||
      name.includes('قصب سكر') ||
      name.includes('أناناس') ||
      name.includes('برتقال') ||
      name.includes('رمان') ||
      name.includes('مانجو') ||
      name.includes('تفاح') ||
      name.includes('شمام') ||
      name.includes('بطيخ')
    ) {
      return 'fruits';
    }

    // E. Check for Mushrooms
    if (name.includes('فطر') || name.includes('مشروم')) {
      return 'seasonal';
    }

    // F. Egg/بيض
    if (name.includes('بيض') && !name.includes('أبيض')) {
      return 'packages';
    }

    // Default for القصيم is qassim
    return 'qassim';
  }

  return 'vegetables';
};

// البيانات الخام لـ 235 منتج كما تم توفيرها بدقة
const rawJsonData = [
  { "id": 1, "category": "الخضروات الأساسية والمحلية", "name_ar": "بطاطس محلي", "name_en": "Potato Local", "description": "بطاطس وطنية طازجة من أجود الأصناف المحلية، تتميز بحجمها المتوسط وقشرتها الرقيقة ولونها الذهبي.", "features": "مصدر غني بالكربوهيدرات والفيتامينات، قوامها مثالي للقلي والسلق والطبخ", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/gF3hHGLG/1-Potato-Local-Kg-3-5.jpg" },
  { "id": 2, "category": "الخضروات الأساسية والمحلية", "name_ar": "بصل أحمر محلي", "name_en": "Red Onion Local", "description": "بصل أحمر طازج من المزارع الوطنية، يتميز بلونه الأرجواني الجذاب ونكهته القوية والحادة قليلاً.", "features": "غني بمضادات الأكسدة، مثالي للسلطات الطازجة والطبخ والشوي", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/twfxBQ3s/2-Red-Onion-Local-Kg-3-5.jpg" },
  { "id": 3, "category": "الخضروات الأساسية والمحلية", "name_ar": "طماطم مدور محلي", "name_en": "Tomato Round Local", "description": "طماطم مدورة وطنية ذات لون أحمر زاهي، تتميز بعصارتها الغنية وطعمها الحلو المميز.", "features": "مصدر ممتاز لفيتامين C ومضادات الأكسدة، مثالية للسلطات والصلصات والطبخ", "origin": "إنتاج وطني (محلي)", "price": 5.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/VYngHR3C/3-Tomato-Round-Local-Kg-5.png" },
  { "id": 4, "category": "الخضروات الأساسية والمحلية", "name_ar": "خيار محلي", "name_en": "Cucumber Local", "description": "خيار وطني طازج ومقرمش، يتميز بقشرته الخضراء الداكنة ولبه الأبيض المنعش.", "features": "منعش ومرطب، منخفض السعرات الحرارية، مثالي للسلطات والمقبلات", "origin": "إنتاج وطني (محلي)", "price": 4.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/8LT44kZT/4-Cucumber-Local-Kg-4-5.png" },
  { "id": 5, "category": "الخضروات الأساسية والمحلية", "name_ar": "جزر محلي", "name_en": "Carrot Local", "description": "جزر وطني طازج بلون برتقالي زاهي، مقرمش وحلو المذاق. يتميز بحجمه المتوسط وجودته العالية.", "features": "غني بفيتامين A والبيتا كاروتين، مثالي للأكل الطازج والسلطات والعصائر", "origin": "إنتاج وطني (محلي)", "price": 4.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/d4kKkjT3/5-Carrot-Local-Kg4-5.png" },
  { "id": 6, "category": "الخضروات الأساسية والمحلية", "name_ar": "كوسة محلي", "name_en": "Zucchini Local", "description": "كوسة وطنية طازجة ذات لون أخضر فاتح، تتميز بملمسها الناعم وطعمها اللذيذ.", "features": "منخفضة السعرات الحرارية، غنية بالألياف، مثالية للحشي والسلق والقلي", "origin": "إنتاج وطني (محلي)", "price": 6.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/trymdkG/6-Kg-6-Zucchini-Local.jpg" },
  { "id": 7, "category": "الخضروات الأساسية والمحلية", "name_ar": "باذنجان أسود مدور", "name_en": "Eggplant Round", "description": "باذنجان أسود مدري وطني، ذو شكل كروي مميز ولون أرجواني داكن لامع.", "features": "غني بالألياف ومضادات الأكسدة، مثالي للشوي والحشي وصنع المتبل", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/JRjF4XzZ/7-Eggplant-Round-Kg-3-5.jpg" },
  { "id": 8, "category": "الخضروات الأساسية والمحلية", "name_ar": "رومي أخضر محلي", "name_en": "Green Capsicum Local", "description": "فلفل رومي أخضر وطني، كبير الحجم وذو جدار سميك، يتميز بنكهته المنعشة والمقرمشة.", "features": "غني بفيتامين C، مثالي للحشو والسلطات والشوي", "origin": "إنتاج وطني (محلي)", "price": 6.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Fbj0TfyP/8-Green-Capsicum-Local-Kg-6.jpg" },
  { "id": 9, "category": "الخضروات الأساسية والمحلية", "name_ar": "فلفل حار أخضر", "name_en": "Green Chili", "description": "فلفل حار أخضر طازج، يتميز بحرارته المتوسطة ونكهته المميزة.", "features": "غني بالفيتامينات، مثالي لإضافة نكهة حارة للطعام", "origin": "إنتاج وطني (محلي)", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/yc78ZCNW/9-Green-Chili-Kg9.jpg" },
  { "id": 10, "category": "الخضروات الأساسية والمحلية", "name_ar": "ثوم محلي", "name_en": "Garlic Local", "description": "ثوم وطني طازج، ذو فصوص كبيرة ورائحة نفاذة، يتميز بنكهته القوية.", "features": "مضاد طبيعي للبكتيريا، غني بمضادات الأكسدة، أساسي في جميع الأطباق", "origin": "إنتاج وطني (محلي)", "price": 10.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/fGnHmvCs/10-Garlic-Local-Kg-10.png" },
  { "id": 11, "category": "الخضروات الأساسية والمحلية", "name_ar": "زهرة (قرنبيط)", "name_en": "Cauliflower", "description": "قرنبيط طازج أبيض ناصع، برؤوس متماسكة وأوراق خضراء طرية.", "features": "غني بفيتامين C والألياف، منخفض الكربوهيدرات، مثالي للشوي والسلق", "origin": "إنتاج وطني (محلي)", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/7JHRLL27/11-Cauliflower-Kg7.jpg" },
  { "id": 12, "category": "الخضروات الأساسية والمحلية", "name_ar": "فاصوليا خضراء", "name_en": "Green Beans", "description": "فاصوليا خضراء طازجة ومقرمشة، ذات لون أخضر زاهي وحجم موحد.", "features": "غنية بالألياف والفيتامينات، مثالية للسلق والقلي والطبخ", "origin": "إنتاج وطني (محلي)", "price": 8.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/qMP3Fwtk/74-Green-Peas-Kg29.png" },
  { "id": 13, "category": "الخضروات الأساسية والمحلية", "name_ar": "بامية محلي", "name_en": "Okra Local", "description": "بامية وطنية طازجة، صغيرة الحجم وطرية، ذات لون أخضر فاتح.", "features": "غنية بالألياف والفيتامينات، مثالية لتحضير اليخنات والطبخات التقليدية", "origin": "إنتاج وطني (محلي)", "price": 15.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/6R2jJG98/13-Okra-Local-Kg15.png" },
  { "id": 14, "category": "الخضروات الأساسية والمحلية", "name_ar": "فطر بوتون أبيض", "name_en": "Button Mushroom White", "description": "فطر بوتون أبيض طازج، صغير الحجم وذو قوام متماسك.", "features": "منخفض السعرات الحرارية، غني بالبروتين والفيتامينات، مثالي للسلطات", "origin": "مستورد", "price": 23.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/zTM0tPKY/14-Button-Mushroom-White-Kg23.jpg" },
  { "id": 15, "category": "الخضروات الأساسية والمحلية", "name_ar": "أفوكادو كينيا", "name_en": "Avocado Kenya", "description": "أفوكادو كيني طازج، ذو قشرة خضراء داكنة، يتميز بقوامه الكريمي ونكهته الغنية.", "features": "غني بالدهون الصحية والفيتامينات، مثالي للسلطات والوجبات الصحية", "origin": "كينيا", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/N2tM34xv/15-Avocado-Kenya-Kg20.jpg" },
  { "id": 16, "category": "الخضروات الأساسية والمحلية", "name_ar": "زنجبيل", "name_en": "Ginger", "description": "زنجبيل طازج بجذور سميكة ورائحة نفاذة، يتميز بنكهته الحارة المنعشة.", "features": "مضاد طبيعي للالتهابات، يعزز المناعة، مثالي للشاي والطبخ", "origin": "مستورد", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/ch83KtFN/16-Ginger-Kg9.png" },
  { "id": 17, "category": "الخضروات الأساسية والمحلية", "name_ar": "لفت محلي", "name_en": "Turnip Local", "description": "لفت وطني طازج أبيض ناصع، ذو شكل كروي وقشرة ناعمة.", "features": "غني بفيتامين C والألياف، مثالي للتخليل والسلق والطبخ", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/NnxP3L9r/17-Turnip-Local-Kg3-5.jpg" },
  { "id": 18, "category": "الخضروات الأساسية والمحلية", "name_ar": "بنجر محلي", "name_en": "Beetroot Local", "description": "بنجر وطني طازج بلون أحمر غامق، بحجم متوسط وقشرة ناعمة.", "features": "غني بالحديد والفولات، مثالي للسلطات والعصائر والطبخ", "origin": "إنتاج وطني (محلي)", "price": 5.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/PZFyD758/18-Beetroot-Local-Kg-5.png" },
  { "id": 19, "category": "الخضروات الأساسية والمحلية", "name_ar": "قرع عسلي", "name_en": "Pumpkin", "description": "قرع عسلي طازج بلون برتقالي زاهي، يتميز بحجمه المتوسط وقوامه الصلب.", "features": "غني بفيتامين A والألياف، مثالي للحساء والحلويات والطبخ", "origin": "إنتاج وطني (محلي)", "price": 5.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Dg4g9Ldx/19-Pumpkin-Kg5-5-c2ed96.png" },
  { "id": 20, "category": "الخضروات الأساسية والمحلية", "name_ar": "باذنجان طويل", "name_en": "Eggplant Long", "description": "باذنجان طويل وطني بلون أرجواني غامق، يتميز بشكله المستدق وقوامه المتماسك.", "features": "قليل البذور، مثالي للشوي والقلي والحشي، يمتص النكهات بشكل رائع", "origin": "إنتاج وطني (محلي)", "price": 5.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/KjDydmBZ/Eggplant-Long-Kg5.png" },
  { "id": 21, "category": "الخضروات الأساسية والمحلية", "name_ar": "باذنجان ابيض", "name_en": "Eggplant White", "description": "باذنجان أبيض نادر وفريد، بلون أبيض كريمي وقشرة ناعمة.", "features": "قوام كريمي، أقل مرة من الباذنجان العادي، مثالي للشوي والتحميص", "origin": "إنتاج وطني (محلي)", "price": 4.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/tMPQbkJC/21-Eggplant-white-Kg4.png" },
  { "id": 22, "category": "الخضروات الأساسية والمحلية", "name_ar": "رومي احمر محلي", "name_en": "Red Capsicum Local", "description": "فلفل رومي أحمر وطني، يتميز بلونه الأحمر الزاهي ونكهته الحلوة المميزة.", "features": "أغنى بالفيتامينات من الأخضر، غني بفيتامين C، مثالي للسلطات", "origin": "إنتاج وطني (محلي)", "price": 8.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/kVx6K2D4/22-Red-Capsicum-Local-Kg8.jpg" },
  { "id": 23, "category": "الخضروات الأساسية والمحلية", "name_ar": "رومي اصفر محلي", "name_en": "Yellow Capsicum Local", "description": "فلفل رومي أصفر وطني، بلون مشمس جذاب ونكهة حلوة وفاكهية.", "features": "غني بمضادات الأكسدة، مثالي لإضفاء لون ونكهة مميزة للأطباق", "origin": "إنتاج وطني (محلي)", "price": 8.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/x8rks4cb/23-Yellow-Capsicum-Local-Kg8.jpg" },
  { "id": 24, "category": "الخضروات الأساسية والمحلية", "name_ar": "بامية صغير محلي", "name_en": "Small Okra Local", "description": "بامية وطنية صغيرة جداً وطرية، تعتبر من أجود أنواع البامية.", "features": "قوام ناعم ولذيذ، مثالية لليخنات والطبخات التقليدية الفاخرة", "origin": "إنتاج وطني (محلي)", "price": 12.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/nqw35zDd/24-Small-Okra-Local-Kg12.png" },
  { "id": 25, "category": "الخضروات الأساسية والمحلية", "name_ar": "فلفل حار احمر", "name_en": "Red Chili", "description": "فلفل حار أحمر طازج، يتميز بلونه الأحمر الزاهي وحرارته المتوسطة إلى عالية.", "features": "غني بفيتامين C، مثالي للصلصات الحارة والطبخ، لون جذاب", "origin": "إنتاج وطني (محلي)", "price": 8.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/KjQRMDFP/25-Red-Chili-Kg8.jpg" },
  { "id": 26, "category": "الخضروات الأساسية والمحلية", "name_ar": "ذرة (كوز)", "name_en": "Corn Cob", "description": "ذرة طازجة على الكوز، حباتها صفراء ذهبية وممتلئة، تتميز بحلاوتها الطبيعية.", "features": "غنية بالألياف والفيتامينات، مثالية للشوي والسلق كوجبة خفيفة", "origin": "إنتاج وطني (محلي)", "price": 12.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/twvTKhhp/26-Corn-Cob-Kg12.png" },
  { "id": 27, "category": "الخضروات الأساسية والمحلية", "name_ar": "قلقاس", "name_en": "Taro", "description": "قلقاس طازج بدرنات بنية اللون، يتميز بقوامه النشوي وطعمه المميز عند الطهي.", "features": "غني بالكربوهيدرات والألياف، مثالي للطبخ والسلق والقلي", "origin": "مستورد", "price": 12.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/bjKbNHLG/27-Taro-Kg12.png" },
  { "id": 28, "category": "الخضروات الأساسية والمحلية", "name_ar": "بركلي محلي", "name_en": "Broccoli Local", "description": "بروكلي وطني طازج برؤوس خضراء مدمجة، يتميز بقوامه المقرمش ونكهته اللذيذة.", "features": "غني بفيتامين C و K ومضادات الأكسدة، مثالي للسلق والتبخير", "origin": "إنتاج وطني (محلي)", "price": 16.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/s9MTsj7W/28-Broccoli-Local-Kg16.jpg" },
  { "id": 29, "category": "الخضروات الأساسية والمحلية", "name_ar": "ملفوف ابيض محلي", "name_en": "White Cabbage Local", "description": "ملفوف أبيض وطني طازج، برأس متماسك وأوراق مقرمشة.", "features": "غني بفيتامين C والألياف، مثالي للسلطات والمخللات والطبخ", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/V08b03dF/29-White-Cabbage-Local-Kg3-5.png" },
  { "id": 30, "category": "الخضروات الأساسية والمحلية", "name_ar": "ملفوف احمر محلي", "name_en": "Red Cabbage Local", "description": "ملفوف أحمر وطني بلون أرجواني جذاب، أوراقه مقرمشة ولذيذة.", "features": "غني بمضادات الأكسدة، مثالي للسلطات الملونة والمخللات", "origin": "إنتاج وطني (محلي)", "price": 4.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/YB31t486/30-Red-Cabbage-Local-Kg4-5.png" },
  { "id": 31, "category": "الخضروات الأساسية والمحلية", "name_ar": "آرتيشوك طازج", "name_en": "Fresh Artichoke", "description": "آرتيشوك طازج، برؤوس خضراء كبيرة، يتميز بطعمه الفريد وقوامه اللذيذ.", "features": "غني بالألياف ومضادات الأكسدة، مثالي للشوي والسلق", "origin": "مستورد", "price": 33.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Lzcr75wf/31-fresh-Artichoke-Kg33.png" },
  { "id": 32, "category": "الخضروات المستوردة والخاصة", "name_ar": "هليون بيبي", "name_en": "Baby Asparagus", "description": "هليون بيبي طازج، براعم رفيعة وطرية، ذات نكهة دقيقة وحساسة.", "features": "غني بالفيتامينات، سريع الطهي، مثالي للقلي السريع أو التبخير", "origin": "مستورد", "price": 9.0, "price_unit": "ريال (للعبوة - PK)", "image_url": "https://i.ibb.co/mVsSYXTd/32-Baby-Asparagus-PK-9.jpg" },
  { "id": 33, "category": "الخضروات المستوردة والخاصة", "name_ar": "هليون جومبو أخضر", "name_en": "Green Jumbo Asparagus", "description": "هليون أخضر جامبو، ذو سيقان سميكة وعصيرية، يتميز بنكهة قوية وقوام ممتاز.", "features": "حجم كبير يضمن قواماً لذيذاً، غني بالألياف، طبق جانبي فاخر", "origin": "مستورد", "price": 55.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/f6TNKP2/33-Green-Jumbo-Asparagus-Kg55.png" },
  { "id": 34, "category": "الخضروات المستوردة والخاصة", "name_ar": "هليون أخضر", "name_en": "Green Asparagus", "description": "هليون أخضر طازج، سيقان متوسطة الحجم، نكهة متوازنة وقوام مقرمش.", "features": "مثالي للسلق أو التبخير، غني بالفيتامينات، نكهة ربيعية منعشة", "origin": "مستورد", "price": 50.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Pv2f3sfC/34-Green-Asparagus-Kg50.png" },
  { "id": 35, "category": "الخضروات المستوردة والخاصة", "name_ar": "هليون أبيض", "name_en": "White Asparagus", "description": "هليون أبيض فاخر، يزرع تحت التربة لمنعه من التمثيل الضوئي.", "features": "أغلى وأندر من الأخضر، نكهة خفيفة وحلوة، تقديم فاخر", "origin": "مستورد", "price": 70.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/NnsQf6ny/35-white-Asparagus-Kg70.png" },
  { "id": 36, "category": "الخضروات المستوردة والخاصة", "name_ar": "أفوكادو (USA)", "name_en": "Avocado (USA)", "description": "أفوكادو أمريكي فاخر، ذو قشرة خشنة وقوام كريمي ونكهة غنية.", "features": "غني بالدهون الصحية، حجم كبير، مثالي للتحضيرات اليومية الصحية", "origin": "الولايات المتحدة الأمريكية", "price": 30.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/bRbWQf0c/36-Avocado-USA-Kg-30.png" },
  { "id": 37, "category": "الخضروات المستوردة والخاصة", "name_ar": "جزر بيبي (هولندا)", "name_en": "Baby Carrot (Holland)", "description": "جزر بيبي هولندي صغير الحجم، مقرمش وحلو المذاق. معبأ بشكل مثالي.", "features": "مثالي للوجبات الخفيفة، غني بفيتامين A، جاهز للأكل طازجاً", "origin": "هولندا", "price": 20.0, "price_unit": "ريال (للعبوة - PK)", "image_url": "https://i.ibb.co/XrdcxTGz/37-Baby-Carrot-Holland-PK20.png" },
  { "id": 38, "category": "الخضروات المستوردة والخاصة", "name_ar": "ذرة بيبي", "name_en": "Baby Corn", "description": "ذرة بيبي صغيرة الحجم، كاملة وكوز صغير، ذات قرمشة عالية.", "features": "مثالية للقلي السريع في الأطباق الآسيوية، غنية بالألياف", "origin": "مستورد (تايلاند عادة)", "price": 5.0, "price_unit": "ريال (للعبوة - PKT)", "image_url": "https://i.ibb.co/b5WX4g0k/38-Baby-Corn-Pkt-5.png" },
  { "id": 39, "category": "الخضروات المستوردة والخاصة", "name_ar": "سبانخ بيبي", "name_en": "Baby Spinach", "description": "سبانخ بيبي طازجة، أوراق صغيرة وطرية، ذات نكهة خفيفة وحلوة.", "features": "غنية بالحديد والفيتامينات، جاهزة للأكل دون تقطيع، للسلطات والسموذي", "origin": "مستورد", "price": 60.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/KjTdXq0R/39-Baby-Spinach-Kg60.png" },
  { "id": 40, "category": "الخضروات المستوردة والخاصة", "name_ar": "براعم فاصوليا", "name_en": "Bean Sprouts", "description": "براعم فاصوليا طازجة، بيضاء ومقرمشة، ذات نكهة منعشة.", "features": "منخفضة السعرات، غنية بالماء، تضاف للأطباق الآسيوية والسلطات", "origin": "مستورد", "price": 8.0, "price_unit": "ريال (للعبوة - PK)", "image_url": "https://i.ibb.co/4gJc18dt/40-Bean-Sprouts-PK8.png" },
  { "id": 41, "category": "الخضروات المستوردة والخاصة", "name_ar": "فاصوليا هاريكوت", "name_en": "Haricot Beans", "description": "فاصوليا هاريكوت خضراء فرنسية، رفيعة وطرية، تعتبر من أفخر الأنواع.", "features": "قوام دقيق ونكهة ممتازة، تطهى بسرعة، طبق جانبي أنيق", "origin": "مستورد", "price": 9.0, "price_unit": "ريال (للعبوة - PK)", "image_url": "https://i.ibb.co/MJWfGSH/41-Haricot-Beans-PK9.png" },
  { "id": 42, "category": "الخضروات المستوردة والخاصة", "name_ar": "بنجر تشيوجيا", "name_en": "Chioggia Beetroot", "description": "بنجر تشيوجيا الإيطالي، يتميز بلونه الداخلي المخطط بالأحمر والأبيض.", "features": "نكهة حلوة خفيفة، يضيف لمسة جمالية مذهلة للسلطات عند التقطيع", "origin": "إيطاليا (مستورد)", "price": 37.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/HLSLZPt5/42-Chioggia-Beetroot-Kg37.png" },
  { "id": 43, "category": "الخضروات المستوردة والخاصة", "name_ar": "بنجر ميني أصفر", "name_en": "Mini Yellow Beetroot", "description": "بنجر أصفر صغير الحجم، بلون ذهبي جذاب ونكهة حلوة معتدلة.", "features": "لا يسبب تلطيخ اليدين، غني بالفيتامينات، يضيف لوناً مميزاً للأطباق", "origin": "مستورد", "price": 22.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/PZXGH1ts/43-Mini-Yellow-Beetroot-PC22.png" },
  { "id": 44, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل أخضر مستورد", "name_en": "Imported Green Pepper", "description": "فلفل أخضر مستورد، كبير الحجم وذو جدار سميك، يتميز بقرمشته العالية.", "features": "مثالي للحشو والسلطات، جودة تصدير ممتازة، نكهة منعشة", "origin": "مستورد", "price": 27.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/XfLDBY00/44-Imported-green-pepper-Kg27.png" },
  { "id": 45, "category": "الخضروات المستوردة والخاصة", "name_ar": "كرنب برسلز", "name_en": "Brussels Sprouts", "description": "كرنب برسلز طازج، برؤوس صغيرة الحجم تشبه الملفوف المصغر.", "features": "غني بفيتامين C وK، مثالي للشوي والتحميص مع زيت الزيتون", "origin": "مستورد", "price": 25.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/zVD9T4s0/45-Brussels-Sprouts-Kg25.png" },
  { "id": 46, "category": "الخضروات المستوردة والخاصة", "name_ar": "كرنب صيني", "name_en": "Chinese Cabbage", "description": "كرنب صيني طازج، برأس طويل وأوراق خضراء فاتحة، يتميز بقوامه المقرمش.", "features": "مثالي للسلطات والقلي السريع، أساسي في المطبخ الآسيوي، غني بالألياف", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/tMjx8gF9/46-Chinese-Cabbage-Kg20.png" },
  { "id": 47, "category": "الخضروات المستوردة والخاصة", "name_ar": "كرنب أبيض مستورد", "name_en": "Imported White Cabbage", "description": "ملفوف أبيض مستورد، برأس كبير ومتماسك، أوراقه مقرمشة ولذيذة.", "features": "مثالي للسلطات والمخللات، يحتفظ بجودته لفترة تخزين طويلة", "origin": "مستورد", "price": 17.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/WNJ6Mb1B/47-Imported-White-Cabbage-Kg17.png" },
  { "id": 48, "category": "الخضروات المستوردة والخاصة", "name_ar": "جزر بيبي أحمر", "name_en": "Red Baby Carrot", "description": "جزر بيبي أحمر صغير الحجم، يتميز بلونه الأحمر الجذاب ونكهته الحلوة.", "features": "غني بالأنثوسيانين المضاد للأكسدة، مثالي للوجبات الخفيفة والسلطات", "origin": "مستورد", "price": 8.0, "price_unit": "ريال (للعبوة - PK)", "image_url": "https://i.ibb.co/jZPT3LYN/48-Red-Baby-Carrot-PK-8.png" },
  { "id": 49, "category": "الخضروات المستوردة والخاصة", "name_ar": "جزر بيبي أصفر", "name_en": "Yellow Baby Carrot", "description": "جزر بيبي أصفر بلون مشمس، حلو المذاق ومقرمش، يضيف لمسة جمالية.", "features": "غني باللوتين، مثالي للأكل الطازج أو التحميص، يحتفظ بلونه", "origin": "مستورد", "price": 36.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/jZPT3LYN/49-Yellow-Baby-Carrot-Kg36.png" },
  { "id": 50, "category": "الخضروات المستوردة والخاصة", "name_ar": "جذور كرفس بيضاء", "name_en": "Celeriac White", "description": "جذور كرفس بيضاء، نكهة عطرية مميزة تشبه الكرفس مع لمسة جوزية.", "features": "مثالية للحساء والمهروس والسلطات، غنية بالألياف، مطبوخة أو نيئة", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/kgg1CRyN/50-Celeriac-White-Kg20.png" },
  { "id": 51, "category": "الخضروات المستوردة والخاصة", "name_ar": "شايوت أخضر", "name_en": "Chayote Green", "description": "شايوت أخضر طازج، ثمرة على شكل كمثرى بلون أخضر فاتح، قوام مقرمش.", "features": "منخفض السعرات، غني بالماء، مثالي للسلطات والقلي والطبخ", "origin": "مستورد", "price": 30.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Z6QDbbsB/51-Chayote-Green-Kg30.png" },
  { "id": 52, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل جالابينو أخضر", "name_en": "Green Jalapeño", "description": "فلفل جالابينو أخضر طازج، يتميز بحرارته المتوسطة ونكهته المميزة.", "features": "حرارة متوازنة، مقرمش، مثالي للصلصات والمخللات المكسيكية", "origin": "مستورد", "price": 30.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/99Lm7PBP/52-Green-Jalapeno-Kg30.jpg" },
  { "id": 53, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل جالابينو أحمر", "name_en": "Red Jalapeño", "description": "فلفل جالابينو أحمر، هو النسخة الناضجة، يتميز بحلاوة إضافية مع الحرارة.", "features": "أقل حدة قليلاً من الأخضر، لون جميل، مثالي للصلصات والسلطات الحارة", "origin": "مستورد", "price": 45.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Nd6ZdQGP/53-Red-Jalapeno-Kg-45.png" },
  { "id": 54, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل جالابينو أصفر", "name_en": "Yellow Jalapeño", "description": "فلفل جالابينو أصفر نادر، يتميز بلونه الزاهي ونكهته الحارة الفاكهية.", "features": "حرارة متوسطة، مثالي لإضفاء لون ونكهة مميزة للأطباق العالمية", "origin": "مستورد", "price": 45.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/q3zpydfX/54-Yellow-Jalapeno-Kg45.png" },
  { "id": 55, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل جالابينو برتقالي", "name_en": "Orange Jalapeño", "description": "فلفل جالابينو برتقالي، صنف نادر وجذاب، حرارة متوازنة.", "features": "يضفي لوناً برتقالياً جميلاً للأطباق، مثالي للتخليل والصلصات المبتكرة", "origin": "مستورد", "price": 45.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/zjwvSTL/55-Orange-Jalapeno-Kg-45.png" },
  { "id": 56, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل أصفر روماني", "name_en": "Roman Yellow Pepper", "description": "فلفل رومي أصفر طويل، يتميز بشكل المستطيل ونكهته الحلوة جداً.", "features": "مثالي للحشو والسلطات، قوام مقرمش، طعم حلو ولذيذ وفاخر", "origin": "مستورد", "price": 22.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/C5nyVxVW/56-Roman-Yellow-Pepper-Kg22.png" },
  { "id": 57, "category": "الخضروات المستوردة والخاصة", "name_ar": "ذرة بيبي طازجة", "name_en": "Fresh Baby Corn", "description": "ذرة بيبي طازجة تماماً، صغيرة الحجم، ذات قرمشة عالية وحلاوة طبيعية.", "features": "طازجة وليست معلبة، مثالية للقلي السريع، منتج توريد فاخر", "origin": "مستورد (تايلاند)", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/4whQJ53f/57-Fresh-Baby-Corn-Kg-80.png" },
  { "id": 58, "category": "الخضروات المستوردة والخاصة", "name_ar": "خيار طويل مستورد", "name_en": "Imported Long Cucumber", "description": "خيار طويل مستورد، ذو قشرة رقيقة وبذور قليلة، مقرمش جداً.", "features": "مثالي للسلطات والتقطيع، قوام متماسك، جودة تصدير من الدرجة الأولى", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/bMyR0zQK/58-Imported-Long-Cucumber-Kg20.png" },
  { "id": 59, "category": "الخضروات المستوردة والخاصة", "name_ar": "فول فافا طازج", "name_en": "Fresh Fava Beans", "description": "فول فافا طازج في قرونه الخضراء، يتميز بحباته الكبيرة ونكهته الزبدية.", "features": "غني بالبروتين والألياف، مثالي للطهي مع اللحوم أو التحضير التقليدي", "origin": "مستورد", "price": 39.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Cs6X0Tq8/59-Fresh-Fava-Beans-Kg39.jpg" },
  { "id": 60, "category": "الخضروات المستوردة والخاصة", "name_ar": "فينل بيبي (شمر)", "name_en": "Baby Fennel", "description": "شمر بيبي صغير الحجم، ذو نكهة عرق السوس الخفيفة وقوام مقرمش.", "features": "مثالي للشوي والسلطات، الأوراق تستخدم كزينة، نكهة منعشة وفريدة", "origin": "مستورد", "price": 21.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/dJ7xrVSf/60-Baby-Fennel-PC21.jpg" },
  { "id": 61, "category": "الخضروات المستوردة والخاصة", "name_ar": "كولرابي مستورد", "name_en": "Imported Kohlrabi", "description": "كولرابي طازج، يشبه اللفت بنكهة الفجل الحلو. مقرمش ولذيذ.", "features": "يمكن تناوله نيئاً مع قليل من الملح، غني بفيتامين C، مثالي للسلطات", "origin": "مستورد", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Cs6X0Tq8/61-Imported-Kohlrabi-Kg18.png" },
  { "id": 62, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر بوتون بني", "name_en": "Brown Button Mushroom", "description": "فطر بوتون بني طازج، يتميز بنكهة أقوى من الأبيض وقوام متماسك.", "features": "نكهة ترابية أغنى، مثالي للشوي والصلصات، غني بالفيتامينات", "origin": "مستورد", "price": 25.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/GQw4ngg5/62-Brown-Button-Mushroom-Kg25.jpg" },
  { "id": 63, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر بورشيني", "name_en": "Porcini Mushroom", "description": "فطر بورشيني الفاخر، ذو نكهة قوية وغنية جداً تعتبر من أفخر النكهات.", "features": "نكهة جوزية مميزة، مثالي للريزوتو والصلصات الكريمية، منتج فاخر", "origin": "مستورد (إيطالي عادة)", "price": 85.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/cSqBfJ4m/63-Porcini-Mushroom-Kg85.png" },
  { "id": 64, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر كستناء", "name_en": "Chestnut Mushroom", "description": "فطر كستناء طازج، بلون بني داكن ونكهة ترابية غنية. قوام متماسك.", "features": "مثالي للشوي والتحمير، يحتفظ بقوامه بعد الطهي، نكهة مميزة", "origin": "مستورد", "price": 30.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/yFFysFwX/64-Chestnut-Mushroom-Kg30.jpg" },
  { "id": 65, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر إنوكي", "name_en": "Enoki Mushroom", "description": "فطر إنوكي أبيض نحيل طويل، برؤوس صغيرة، قوام مقرمش ونكهة خفيفة.", "features": "يضاف في آخر الطهي، مثالي للشوربات والقلي السريع الآسيوي", "origin": "مستورد", "price": 20.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/1fBxg5jQ/65-Enoki-Mushroom-PC-20.png" },
  { "id": 66, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر بورتوبيلو", "name_en": "Portobello Mushroom", "description": "فطر بورتوبيلو كبير الحجم، ذو قبعة عريضة ونكهة غنية ولحمية.", "features": "بديلاً ممتازاً للحم، مثالي للشوي كاملة، يمكن حشوها، نكهة قوية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/n83T0y04/66-Portobello-Mushroom-Kg35.png" },
  { "id": 67, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر شيتاكي", "name_en": "Shiitake Mushroom", "description": "فطر شيتاكي آسيوي، ذو قبعة بنية ونكهة مدخنة غنية.", "features": "غني بالعناصر الغذائية، مثالي للقلي السريع واليخنات، نكهة أومامي", "origin": "مستورد", "price": 74.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/vCwgTZMy/67-Shiitake-Mushroom-Kg74.png" },
  { "id": 68, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر شيميجي أبيض", "name_en": "White Shimeji Mushroom", "description": "فطر شيميجي أبيض صغير الحجم، ينمو في عناقيد، نكهة جوزية خفيفة.", "features": "مثالي للقلي السريع، لا يحتاج لتقطيع، يضيف نكهة رائعة للأطباق", "origin": "مستورد", "price": 48.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/vCh8Dtc4/68-white-Shimeji-Mushroom-Kg48.png" },
  { "id": 69, "category": "الخضروات المستوردة والخاصة", "name_ar": "بصل لؤلؤي أحمر", "name_en": "Red Pearl Onion", "description": "بصل لؤلؤي أحمر صغير جداً، بحجم حبة الكرز، يتميز بحلاوته.", "features": "حجم صغير مثالي للتقديم الفاخر، نكهة حلوة خفيفة، للشوي الكامل", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/BKg0XYyr/69-Red-Pearl-Onion-Kg21.png" },
  { "id": 70, "category": "الخضروات المستوردة والخاصة", "name_ar": "بصل لؤلؤي أبيض", "name_en": "White Pearl Onion", "description": "بصل لؤلؤي أبيض صغير، بنفس حجم الأحمر، يتميز بنكهة معتدلة.", "features": "مثالي لتحضير اليخنات الصغيرة أو التحميص، يضيف لمسة فاخرة", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/nqN1hkfq/70-white-Pearl-Onion-Kg21.png" },
  { "id": 71, "category": "الخضروات المستوردة والخاصة", "name_ar": "بصل أحمر جومبو", "name_en": "Jumbo Red Onion", "description": "بصل أحمر جامبو كبير الحجم، يتميز بحجمه الضخم ونكهته القوية.", "features": "حجم كبير يقلل الهدر في المطابخ الكبرى، نكهة ممتازة للطبخ والشوي", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/VW4zv8jz/71-Jumbo-Red-Onion-Kg-21.png" },
  { "id": 72, "category": "الخضروات المستوردة والخاصة", "name_ar": "بصل شالوت", "name_en": "Shallots", "description": "بصل شالوت صغير، نكهة معتدلة وحلوة، مثالي للصلصات الراقية.", "features": "نكهة فاخرة، سهل التقشير، غني بمضادات الأكسدة، للطبخ الفرنسي والعالمي", "origin": "مستورد", "price": 42.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/XZ8WQSSs/72-Shallots-Kg42.jpg" },
  { "id": 73, "category": "الخضروات المستوردة والخاصة", "name_ar": "بصل أبيض مستورد", "name_en": "Imported White Onion", "description": "بصل أبيض مستورد، نكهة قوية وحادة، مثالي للطبخ والقلي.", "features": "قوام صلب، نكهة مركزة، غني بالألياف، أساسي في معظم الأطباق العالمية", "origin": "مستورد", "price": 15.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/4npF3Q3c/73-Imported-White-Onion-Kg15.png" },
  { "id": 74, "category": "الخضروات المستوردة والخاصة", "name_ar": "بازلاء خضراء", "name_en": "Green Peas", "description": "بازلاء خضراء طازجة في قرونها، حلاوة طبيعية وقوام مقرمش.", "features": "غنية بالبروتين النباتي، طعم حلو، مثالية للسلطات والطبخ والشوربات", "origin": "مستورد", "price": 29.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/qMP3Fwtk/74-Green-Peas-Kg29.png" },
  { "id": 75, "category": "الخضروات المستوردة والخاصة", "name_ar": "بطاطس بيبي", "name_en": "Baby Potato", "description": "بطاطس صغيرة الحجم، قشرة رقيقة وقوام كريمي عند الطبخ.", "features": "تطهى كاملة، مثالية للشواء والتحمير، نكهة غنية، قشرة صالحة للأكل", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/kfC20ry/75-baby-potato-Kg21.jpg" },
  { "id": 76, "category": "الخضروات المستوردة والخاصة", "name_ar": "بطاطس بيبي حمراء", "name_en": "Red Baby Potato", "description": "بطاطس صغيرة بقشرة حمراء، قوام متماسك ونكهة مميزة.", "features": "مثالية للسلطات والتحمير، مظهر جذاب، غنية بالفيتامينات، قوام شمعي", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/fGQQBjXD/76-Red-baby-potato-Kg21.jpg" },
  { "id": 77, "category": "الخضروات المستوردة والخاصة", "name_ar": "بطاطس بيبي بيضاء", "name_en": "White Baby Potato", "description": "بطاطس صغيرة بقشرة بيضاء، نكهة معتدلة وقوام ناعم.", "features": "سريعة النضج، مثالية للسلق والهرس الخفيف، طعم كلاسيكي لذيذ", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Xx4VNS1j/77-White-baby-potato-Kg21.png" },
  { "id": 78, "category": "الخضروات المستوردة والخاصة", "name_ar": "بطاطس حلوة (USA)", "name_en": "Sweet Potato (USA)", "description": "بطاطس حلوة أمريكية، لب برتقالي غني وحلاوة طبيعية فائقة.", "features": "غنية جداً بفيتامين A، مثالية للشواء والحلويات، قوام كريمي ناعم", "origin": "الولايات المتحدة الأمريكية", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/TMqm4bQk/78-Sweet-potato-USA-Kg21.png" },
  { "id": 79, "category": "الخضروات المستوردة والخاصة", "name_ar": "رومانيسكو ميني", "name_en": "Mini Romanesco", "description": "رومانيسكو صغير، شكل هندسي فريد ولون أخضر زاهي.", "features": "نكهة جوزية خفيفة، مظهر رائع في الأطباق، غني بالألياف وفيتامين C", "origin": "مستورد", "price": 37.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/jkgW7wpc/79-Mini-Romanesco-Kg37.png" },
  { "id": 80, "category": "الخضروات المستوردة والخاصة", "name_ar": "كرنب سافوي", "name_en": "Savoy Cabbage", "description": "كرنب سافوي بأوراق مجعدة ونكهة معتدلة وحلوة.", "features": "أوراق مرنة مثالية للمحاشي، قوام مقرمش، غني بالفيتامينات والمعادن", "origin": "مستورد", "price": 22.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/zhnVyYGQ/80-Savoy-Cabbage-Kg22.png" },
  { "id": 81, "category": "الخضروات المستوردة والخاصة", "name_ar": "بازلاء الثلج", "name_en": "Snow Peas", "description": "بازلاء الثلج المسطحة، تؤكل كاملة بقرونها، حلاوة وقرمشة.", "features": "مثالية للطبخ السريع (ستير فراي)، غنية بالألياف، طعم منعش ومقرمش", "origin": "مستورد", "price": 37.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/nM9J8d5L/81-Snow-Peas-Kg37.png" },
  { "id": 82, "category": "الخضروات المستوردة والخاصة", "name_ar": "قرع أكرون أخضر", "name_en": "Green Akron Squash", "description": "قرع أكرون أخضر، نكهة جوزية حلوة وقوام متماسك.", "features": "مثالي للشواء والحشو، غني بالبوتاسيوم، قشرة صلبة ولب برتقالي جميل", "origin": "مستورد", "price": 26.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/hJFgV0gW/82-Green-Akron-Squash-Kg26.png" },
  { "id": 83, "category": "الخضروات المستوردة والخاصة", "name_ar": "قرع باترنوت", "name_en": "Butternut Squash", "description": "قرع باترونت بشكل الكمثرى، لب برتقالي ناعم وحلاوة عالية.", "features": "مثالي للشوربات الكريمية، غني بفيتامين A، قوام زبدي ونكهة غنية", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/WNP2jyTm/83-Butternut-squash-Kg21.png" },
  { "id": 84, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم كومب برتقالي", "name_en": "Orange Kumquat Tomato", "description": "طماطم صغيرة برتقالية بشكل الكومكوات، حلاوة ونكهة عطرية.", "features": "مظهر جذاب، طعم حلو، مثالية للسلطات الراقية وتزيين الأطباق", "origin": "مستورد", "price": 38.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/b5HBYJRd/84-Orange-Kumquat-Tomato-Kg38.png" },
  { "id": 85, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم كومب حمراء", "name_en": "Red Kumquat Tomato", "description": "طماطم صغيرة حمراء بشكل الكومكوات، نكهة مركزة وحلاوة.", "features": "قوام متماسك، طعم غني، مثالية للسلطات والمقبلات الفاخرة", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/ZR36V7jX/85-Red-Kumquat-Tomato-Kg35.png" },
  { "id": 86, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم كرزية صفراء", "name_en": "Yellow Cherry Tomato", "description": "طماطم كرزية صفراء صغيرة، حلاوة عالية وحموضة منخفضة.", "features": "لون زاهي، طعم منعش، مثالية للسلطات الملونة ووجبات الأطفال الصحية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/MbZcw0N/86-Yellow-Cherry-Tomato-Kg35.png" },
  { "id": 87, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم هيرلوم", "name_en": "Heirloom Tomato", "description": "طماطم هيرلوم متنوعة الأشكال والألوان، نكهة أصيلة وغنية.", "features": "أفضل نكهة طماطم، قوام لحمي، مثالية للسلطات الفاخرة والتقديم", "origin": "مستورد", "price": 37.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/nqfx9cVg/87-Heirloom-Tomato-Kg37.jpg" },
  { "id": 88, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم مارماند", "name_en": "Marmande Tomato", "description": "طماطم مارماند كبيرة ومضلعة، نكهة فرنسية كلاسيكية غنية.", "features": "قوام لحمي ممتاز، طعم متوازن، مثالية للتقطيع في السندويشات والسلطات", "origin": "مستورد", "price": 40.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/x88RjdJD/88-Marmande-Tomato-Kg40.png" },
  { "id": 89, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم روما بلوم", "name_en": "Roma Plum Tomato", "description": "طماطم روما بيضاوية، لب سميك وبذور قليلة، مثالية للصلصات.", "features": "نكهة مركزة، قوام صلب، مثالية للطبخ وصناعة صلصة الطماطم المنزلية", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/tTb3SkQM/89-Roma-Plum-Tomato-Kg20.png" },
  { "id": 90, "category": "الخضروات المستوردة والخاصة", "name_ar": "كركم طازج", "name_en": "Fresh Turmeric", "description": "جذور الكركم الطازجة، لون برتقالي مكثف ونكهة ترابية عطرية.", "features": "مضاد قوي للالتهابات، نكهة مميزة، للعصائر الصحية والطبخ الآسيوي", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/gMsJcWRk/90-Fresh-Turmeric-Kg-20.png" },
  { "id": 91, "category": "الخضروات المستوردة والخاصة", "name_ar": "لفت ميني مستورد", "name_en": "Imported Mini Turnip", "description": "لفت صغير مستورد، نكهة معتدلة وقوام مقرمش.", "features": "يؤكل طازجاً أو مخللاً، غني بالألياف، مظهر أنيق في الأطباق الراقية", "origin": "مستورد", "price": 122.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/zW1rdJcC/91-Imported-Mini-Turnip-Kg122.png" },
  { "id": 92, "category": "الخضروات المستوردة والخاصة", "name_ar": "كوسا بيبي مع الزهرة", "name_en": "Baby Zucchini With Flower", "description": "كوسا صغيرة جداً مع زهرتها الصفراء، فاخرة جداً.", "features": "تستخدم في المطاعم الراقية، الزهرة قابلة للحشو، نكهة رقيقة جداً", "origin": "مستورد", "price": 27.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/fzDY3NVb/92-Baby-Zucchini-With-Flower-Kg27.png" },
  { "id": 93, "category": "الفواكه", "name_ar": "موز", "name_en": "Banana", "description": "موز طازج، حلاوة طبيعية وقوام كريمي، غني بالبوتاسيوم.", "features": "مصدر سريع للطاقة، مثالي للأطفال والرياضيين، وجبة خفيفة مثالية", "origin": "مستورد", "price": 6.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/fzDY3NVb/93-Banana-Kg6-5.png" },
  { "id": 94, "category": "الفواكه", "name_ar": "تفاح سكري", "name_en": "Sukari Apple", "description": "تفاح سكري طازج، حلاوة فائقة وقوام مقرمش جداً.", "features": "طعم حلو جداً، قشرة رقيقة، مثالي للأكل الطازج، محصول عالي الجودة", "origin": "مستورد", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/BHvYtKK6/94-Sukari-Apple-Kg-7.png" },
  { "id": 95, "category": "الفواكه", "name_ar": "تفاح أخضر", "name_en": "Green Apple", "description": "تفاح أخضر (جراني سميث)، حموضة منعشة وقوام صلب مقرمش.", "features": "حامض ومنعش، غني بالألياف، مثالي للسلطات والعصائر والطبخ", "origin": "مستورد", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/yczsJk1j/95-Green-Apple-Kg-7.png" },
  { "id": 96, "category": "الفواكه", "name_ar": "تفاح أحمر", "name_en": "Red Apple", "description": "تفاح أحمر طازج، حلاوة متوازنة وقوام مقرمش، لون جذاب.", "features": "طعم كلاسيكي حلو، غني بالفيتامينات، مثالي للأكل اليومي والوجبات الخفيفة", "origin": "مستورد", "price": 7.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/DgHyL87b/96-Red-Apple-Kg7-5.png" },
  { "id": 97, "category": "الفواكه", "name_ar": "برتقال عصير", "name_en": "Juice Orange", "description": "برتقال مخصص للعصر، قشرة رقيقة وكمية كبيرة من العصارة.", "features": "غني جداً بفيتامين C، نكهة منعشة، مثالي لبدء يومك بعصير طازج", "origin": "مستورد", "price": 5.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/qZJNzb1/97-Juice-Orange-Kg5.png" },
  { "id": 98, "category": "الفواكه", "name_ar": "برتقال أبو صرة", "name_en": "Navel Orange", "description": "برتقال أبو صرة، سهل التقشير وبدون بذور، حلاوة عالية.", "features": "مثالي للأكل الطازج، فصوص كبيرة وعصيرية، طعم حلو ومنعش", "origin": "مستورد", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/DDQBNCFB/98-Navel-Orange-Kg7.png" },
  { "id": 99, "category": "الفواكه", "name_ar": "مانجو تيمور", "name_en": "Mango Taimur", "description": "مانجو تيمور فاخر، حلاوة مركزة وقوام زبدي بدون ألياف.", "features": "من أرقى أنواع المانجو، رائحة عطرية نفاذة، طعم استوائي لا يقاوم", "origin": "مستورد", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/qLYbFL1w/99-Mango-Taimur-Kg-18.png" },
  { "id": 100, "category": "الفواكه", "name_ar": "فراولة مصري", "name_en": "Egyptian Strawberry", "description": "فراولة مصرية طازجة، لون أحمر زاهي ونكهة حلوة.", "features": "عطرية، مثالية للعصائر والحلويات، محصول طازج ومختار بعناية", "origin": "مصر", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/PZ697sZR/100-Egyptian-Strawberry-Kg20.jpg" },
  { "id": 101, "category": "الفواكه", "name_ar": "كيوي", "name_en": "Kiwi", "description": "كيوي طازج، لب أخضر منعش وبذور سوداء صغيرة، حامض حلو.", "features": "غني جداً بفيتامين C، يساعد على الهضم، مثالي لسلطات الفواكه", "origin": "مستورد", "price": 12.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/xKyCZKVz/101-Kiwi-Kg12.jpg" },
  { "id": 102, "category": "الفواكه", "name_ar": "عنب أخضر محلي", "name_en": "Local Green Grapes", "description": "عنب أخضر وطني طازج، حلاوة طبيعية وقوام مقرمش.", "features": "بدون بذور، منعش، محصول محلي طازج، مثالي كوجبة خفيفة صحية", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/2YWCmfTJ/102-Local-Green-Grapes-Kg13.png" },
  { "id": 103, "category": "الفواكه", "name_ar": "أناناس كبير", "name_en": "Large Pineapple", "description": "أناناس كبير الحجم، حلاوة استوائية ونكهة منعشة.", "features": "عصيري، غني بفيتامين C والبروميلين، مثالي للعصائر والتحلية", "origin": "مستورد", "price": 10.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/bMCZHn6Q/103-Large-Pineapple-Kg10.png" },
  { "id": 104, "category": "الفواكه", "name_ar": "رمان محلي", "name_en": "Local Pomegranate", "description": "رمان وطني طازج، حبات حمراء ياقوتية وحلاوة مع حموضة خفيفة.", "features": "غني بمضادات الأكسدة، طعم أصيل، محصول محلي فاخر ومنعش", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/fYKj3hbn/104-Local-Pomegranate-Kg13.png" },
  { "id": 105, "category": "الفواكه", "name_ar": "شمام", "name_en": "Sweet Melon", "description": "شمام أخضر فاتح من الخارج، حلاوة منعشة وقوام عصيري.", "features": "طعم حلو ومنعش، غني بالفيتامينات، مثالي للسلطات والحلويات الباردة", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/NgN5n6QW/105-Sweet-Melon-Kg-3-5.png" },
  { "id": 106, "category": "الفواكه", "name_ar": "بطيخ مدور محلي", "name_en": "Round Watermelon", "description": "بطيخ أحمر مدور وطني، بلحم أحمر غامق، حلو جداً.", "features": "منعش، يروي العطش، غني بالماء، حلاوة طبيعية عالية، مثالي للصيف", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/5WtDJjCg/106-Round-Watermelon-Kg3-5.png" },
  { "id": 107, "category": "الفواكه", "name_ar": "ليمون كبير محلي", "name_en": "Large Local Lemon", "description": "ليمون وطني كبير الحجم، أصفر زاهي، كثير العصارة وحامض.", "features": "غني بفيتامين C، نكهة قوية ومميزة، للعصائر والطبخ والمخللات", "origin": "إنتاج وطني (محلي)", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/5X6rcLhp/107-Large-Local-Lemon-Kg9.png" },
  { "id": 108, "category": "الفواكه", "name_ar": "ليمون صغير محلي", "name_en": "Small Local Lemon", "description": "ليمون وطني صغير (بنزهير)، قشرة رقيقة ورائحة عطرية.", "features": "حامض جداً ولذيذ، مثالي للمشروبات، يعصر بسهولة، نكهة مركزة", "origin": "إنتاج وطني (محلي)", "price": 4.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/jZyXFRf3/108-Small-Local-Lemon-PC4.png" },
  { "id": 109, "category": "الفواكه", "name_ar": "مشمش مستورد (USA)", "name_en": "Imported Apricot", "description": "مشمش أمريكي طازج برتقالي محمر، ناعم وحلو الملمس.", "features": "رائحة عطرية، غني بفيتامين A، للأكل الطازج أو صناعة الحلويات", "origin": "الولايات المتحدة الأمريكية", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/rG8L3szH/109-USA-Imported-Apricot-Kg-35.png" },
  { "id": 110, "category": "الفواكه", "name_ar": "توت أسود (USA)", "name_en": "Blackberries", "description": "توت أسود أمريكي طازج، حبات كبيرة لامعة، نكهة غنية.", "features": "حامض حلو، غني بمضادات الأكسدة، مثالي للحلويات الراقية والعصائر", "origin": "الولايات المتحدة الأمريكية", "price": 15.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/TMsHQGGY/110-Blackberries-PC-15.png" },
  { "id": 111, "category": "الفواكه", "name_ar": "توت أزرق مستورد", "name_en": "Blueberries", "description": "توت أزرق طازج، حبات صغيرة داكنة، نكهة حلوة حمضية.", "features": "سوبر فود، غني بمضادات الأكسدة، مثالي للإفطار والحلويات الصحية", "origin": "مستورد", "price": 14.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/np1NFp6/111-Blueberries-PC-14.png" },
  { "id": 112, "category": "الفواكه", "name_ar": "شمام كانتالوب", "name_en": "Cantaloupe Melon", "description": "شمام كانتالوب بلحم برتقالي، رائحة عطرية وحلاوة عالية.", "features": "طعم غني وحلو، غني بفيتامين A، مثالي للسلطات والتحلية", "origin": "مستورد", "price": 22.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/PvGJMyw6/112-Cantaloupe-Melon-Kg-22.png" },
  { "id": 113, "category": "الفواكه", "name_ar": "كرز مستورد (USA)", "name_en": "Cherry (USA)", "description": "كرز أمريكي طازج، بلون أحمر غامق، حلاوة فائقة وقوام صلب.", "features": "فاكهة فاخرة، حجم كبير، مثالية للتقديم والمناسبات، نكهة مركزة", "origin": "الولايات المتحدة الأمريكية", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/ycMdnPSg/113-USA-Sherry-Kg-80.png" },
  { "id": 114, "category": "الفواكه", "name_ar": "كرز أسترالي", "name_en": "Australian Cherry", "description": "كرز أسترالي فاخر، بلون أحمر غامق، حلاوة وقرمشة عالية.", "features": "أجود أنواع الكرز، حجم كبير جداً، نكهة استثنائية وفريدة", "origin": "أستراليا", "price": 50.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/p6X3x5Xp/114-Australian-Cherry-Kg-50.png" },
  { "id": 115, "category": "الفواكه", "name_ar": "كرانبيري طازج", "name_en": "Fresh Cranberry", "description": "توت الكرانبيري الطازج بلون أحمر داكن، طعم حامض مميز.", "features": "غني بمضادات الأكسدة، للصلصات والعصائر والمخبوزات الصحية", "origin": "مستورد", "price": 60.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/F4JyPwBq/115-Fresh-Cranberry-Kg-60.png" },
  { "id": 116, "category": "الفواكه", "name_ar": "ثمرة التنين", "name_en": "Dragon Fruit", "description": "فاكهة التنين الجذابة، قشرة وردية ولب عصيري حلو.", "features": "مظهر رائع، غنية بالألياف، منخفضة السعرات، للسلطات والعصائر", "origin": "مستورد", "price": 38.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/wZBQ8BzK/116-Dragon-Fruit-Kg-38.png" },
  { "id": 117, "category": "الفواكه", "name_ar": "دوريان مستورد", "name_en": "Imported Durian", "description": "دوريان، ملك الفواكه، قشرة شوكية ولب كريمي غني.", "features": "نكهة فريدة وقوية جداً، غني بالطاقة، قوام زبدي دسم وفارخ", "origin": "مستورد", "price": 38.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/x8rttNMs/117-imported-Durian-Kg-38.png" },
  { "id": 118, "category": "الفواكه", "name_ar": "كمثرى فوريل", "name_en": "Forelle Pear", "description": "كمثرى فوريل صغيرة، لون أصفر بنقاط حمراء، نكهة حلوة منعشة.", "features": "قوام مقرمش، حجم مثالي، قشرة رقيقة وطعم ممتاز للأطفال", "origin": "مستورد", "price": 10.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/QvTVpKH6/118-Forelle-Peagr-Kg-10.png" },
  { "id": 119, "category": "الفواكه", "name_ar": "غرانديلا مستوردة", "name_en": "Imported Grandilla", "description": "غرانديلا (العاطفة الحلوة)، قشرة برتقالية صلبة ولب حلو.", "features": "نكهة استوائية رائعة، تؤكل بملعقة، غنية بالفيتامينات وبذور مقرمشة", "origin": "مستورد", "price": 33.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/qZ8w9zV/119-Imported-Granadilla-Kg-33.png" },
  { "id": 120, "category": "الفواكه", "name_ar": "جريب فروت وردي", "name_en": "Pink Grapefruit", "description": "جريب فروت وردي كبير، لب وردي ونكهة حامضة مرة منعشة.", "features": "غني بفيتامين C، مثالي للإفطار الصحي والعصائر المنعشة للجسم", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/RpRWqDcg/120-Pink-Grapefruit-Kg-20.png" },
  { "id": 121, "category": "الفواكه", "name_ar": "شمام هوني ديو", "name_en": "Honeydew Melon", "description": "شمام هوني ديو أخضر فاتح، حلاوة عالية جداً وقوام عصيري.", "features": "حلاوة مركزة، منعش، مثالي للحلويات الصيفية وسلطات الفواكه", "origin": "مستورد", "price": 22.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/JW45xXt9/121-Honeydew-Melon-Kg-22.png" },
  { "id": 122, "category": "الفواكه", "name_ar": "كيوانو هولندا", "name_en": "Kiwano (Holland)", "description": "كيوانو بقشرة برتقالية شوكية ولب أخضر منعش.", "features": "شكل غريب وج جذاب، نكهة خيار وموز، غني بالماء ومنعش جداً", "origin": "هولندا", "price": 60.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/rR0Tv8CL/122-Kiwano-Holland-Kg-60.png" },
  { "id": 123, "category": "الفواكه", "name_ar": "كومكوات مستورد", "name_en": "Imported Kumquat", "description": "كومكوات (برتقال ذهبي) صغير، يؤكل بقشره، نكهة حلوة حامضة.", "features": "تؤكل كاملة، مثالية للمربى أو التزيين، غنية جداً بفيتامين C", "origin": "مستورد", "price": 52.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/FkNXSdTs/123-Imported-Kumquat-Kg-52.jpg" },
  { "id": 124, "category": "الفواكه", "name_ar": "لونغان مستورد", "name_en": "Imported Longan", "description": "لونغان (عين التنين) فاكهة استوائية صغيرة حلوة.", "features": "لب شفاف حلو، تشبه الليتشي، منعشة ومثالية كوجبة خفيفة استوائية", "origin": "مستورد", "price": 37.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/JjZSYhKQ/124-Imported-Longan-Kg-37.png" },
  { "id": 125, "category": "الفواكه", "name_ar": "ليتشي مستورد", "name_en": "Imported Lychee", "description": "ليتشي طازج بقشرة خشنة ولب أبيض عصيري.", "features": "نكهة زهرية حلوة، فاكهة صيفية فاخرة، غنية جداً بفيتامين C", "origin": "مستورد", "price": 45.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/CrMq0qK/125-Imported-Lychee-Kg-45.png" },
  { "id": 126, "category": "الفواكه", "name_ar": "مانغوستين مستورد", "name_en": "Imported Mangosteen", "description": "مانغوستين، ملكة الفواكه، لب أبيض ناعم وحلو حامض.", "features": "لب يذوب في الفم، غني بمضادات الأكسدة، فاكهة استوائية فاخرة", "origin": "مستورد", "price": 36.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/h1gxfTDv/126-Imported-Mangosteen-Kg36.png" },
  { "id": 127, "category": "الفواكه", "name_ar": "نكتارين (USA)", "name_en": "Nectarine (USA)", "description": "نكتارين أمريكي، قشرة ناعمة وحلاوة مركزة.", "features": "قوام صلب مقرمش، نكهة حلوة قوية، مثالي للأكل الطازج، غني بالفيتامينات", "origin": "الولايات المتحدة الأمريكية", "price": 32.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/mVQ4wszm/127-Nectarine-USA-Kg32.png" },
  { "id": 128, "category": "الفواكه", "name_ar": "باسيون فروت", "name_en": "Passion Fruit", "description": "فاكهة العاطفة، لب أصفر وبذور مقرمشة، نكهة استوائية عطرية.", "features": "نكهة حامضة حلوة قوية، مثالية للصلصات والعصائر والحلويات الفاخرة", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/cG2dcWC/128-Passion-Fruit-Kg-35.png" },
  { "id": 129, "category": "الفواكه", "name_ar": "خوخ مستورد (USA)", "name_en": "Imported Peach", "description": "خوخ أمريكي طازج، بلون أصفر محمر وحلاوة عالية.", "features": "عصيري، غني بالألياف، نكهة صيفية رائعة، مثالي للأكل والحلويات", "origin": "الولايات المتحدة الأمريكية", "price": 32.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/RG0W1z4j/129-Imported-Peach-Kg-32.png" },
  { "id": 130, "category": "الفواكه", "name_ar": "فيزاليس (حرنكش)", "name_en": "Physalis", "description": "فيزاليس بقشرة ورقية، ثمرة صغيرة برتقالية حامضة حلوة.", "features": "غني بفيتامين C، مثالي لتزيين الحلويات الراقية، نكهة فريدة ومميزة", "origin": "مستورد", "price": 65.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/R4ZC6tq6/130-Physalis-Kg-65.png" },
  { "id": 131, "category": "الفواكه", "name_ar": "رامبوتان مستورد", "name_en": "Imported Rambutan", "description": "رامبوتان بقشرة حمراء شعيرية ولب أبيض حلو.", "features": "سهل التقشير، نكهة استوائية منعشة تشبه الليتشي، مظهر جذاب جداً", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/MwGmwtm/131-Imported-Rambutan-Kg-35.png" },
  { "id": 132, "category": "الفواكه", "name_ar": "توت أحمر مستورد", "name_en": "Red Raspberries", "description": "توت أحمر طازج، بلون أحمر زاهي ونكهة حلوة حمضية.", "features": "غني بمضادات الأكسدة، مثالي للحلويات والتزيين الفاخر، نكهة مميزة", "origin": "مستورد", "price": 15.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/Ld31Z5ZS/132-Red-Raspberries-PC-15.png" },
  { "id": 133, "category": "الفواكه", "name_ar": "كشمش أحمر", "name_en": "Red Currants", "description": "كشمش أحمر طازج، حبات حمراء شفافة في عناقيد.", "features": "نكهة حامضة منعشة، مثالي لصنع الجيلي والمربى وتزيين الحلويات", "origin": "مستورد", "price": 17.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/mCvfYCq0/133-Red-Currants-PC-17.png" },
  { "id": 134, "category": "الفواكه", "name_ar": "فاكهة النجمة", "name_en": "Star Fruit", "description": "فاكهة النجمة (كارامبولا)، شكل نجمة عند التقطيع.", "features": "لون أصفر، نكهة حامضة حلوة، جمالية رائعة لتزيين الكوكتيل والسلطات", "origin": "مستورد", "price": 90.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/LhkwF4qb/134-Star-Fruit-Kg-90.png" },
  { "id": 135, "category": "الفواكه", "name_ar": "فراولة (USA)", "name_en": "Strawberry (USA)", "description": "فراولة أمريكية فاخرة، كبيرة الحجم وحلوة جداً.", "features": "جودة عالية، عصيرية، لون أحمر زاهي، مثالية للحلويات الفاخرة", "origin": "الولايات المتحدة الأمريكية", "price": 47.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Wp2CtZp1/135-Strawberry-USA-Kg-47.png" },
  { "id": 136, "category": "الفواكه", "name_ar": "تاماريلو مستورد", "name_en": "Imported Tamarillo", "description": "تاماريلو (شجرة الطماطم)، لب حامض حلو يشبه الطماطم.", "features": "تؤكل بعد التقشير، غنية بالفيتامينات، مثالية للعصائر والصلصات", "origin": "مستورد", "price": 53.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Vcmfk1t0/138-Imported-Tamarillo-Kg-53.png" },
  { "id": 137, "category": "الفواكه", "name_ar": "نكتارين محلي", "name_en": "Local Nectarine", "description": "نكتارين وطني طازج، قشرة ناعمة وحلاوة طبيعية.", "features": "محصول محلي طازج، نكهة رائعة، مثالي للأكل اليومي، جودة عالية", "origin": "إنتاج وطني (محلي)", "price": 16.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/mfn59br/137-Local-Nectarine-Kg-53.png" },
  { "id": 138, "category": "الفواكه", "name_ar": "بخارة أسود", "name_en": "Black Plum", "description": "بخارة سوداء (برقوق) طازجة، نكهة حلوة مع حموضة خفيفة.", "features": "قوام عصيري، غنية بالألياف، مثالية كوجبة خفيفة صحية ومفيدة", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/2TfdJfY/138-Black-Plum-Kg-13.png" },
  { "id": 139, "category": "الفواكه", "name_ar": "بخارة أحمر", "name_en": "Red Plum", "description": "بخارة حمراء طازجة، لون أحمر جذاب وحلاوة عالية.", "features": "عصيرية، مثالية للحلويات والسلطات، محصول محلي طازج وممتاز", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/RXbkR6f/139-Red-Plum-Kg-13.png" },
  { "id": 140, "category": "الفواكه", "name_ar": "تفاح أصفر", "name_en": "Yellow Apple", "description": "تفاح أصفر طازج، حلاوة عالية ونكهة عطرية، قشرة رقيقة.", "features": "قوام مقرمش، طعم حلو مميز، مثالي للأكل اليومي للأطفال والكبار", "origin": "مستورد", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/202ndPpf/140-Yellow-Apple-Kg-7.png" },
  { "id": 141, "category": "الفواكه", "name_ar": "مشمش محلي", "name_en": "Local Apricot", "description": "مشمش وطني طازج برتقالي، ناعم وحلو وعطري.", "features": "محصول محلي موسمي، نكهة رائعة، مثالي للأكل الطازج وصنع المربى", "origin": "إنتاج وطني (محلي)", "price": 16.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/zWz2mB7r/141-Local-Apricot-Kg-16.png" },
  { "id": 142, "category": "الفواكه", "name_ar": "تين شوكي", "name_en": "Prickly Pear", "description": "تين شوكي بقشرة شوكية ولب أحمر حلو عصيري.", "features": "منعش جداً، غني بالألياف، محصول محلي صيفي مميز، يروي العطش", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/C5QBbpgy/142-Prickly-pear-Kg-13.png" },
  { "id": 143, "category": "الفواكه", "name_ar": "قشطة", "name_en": "Custard Apple", "description": "قشطة بقشرة خضراء مزركشة ولب كريمي حلو جداً.", "features": "نكهة الكاسترد، غنية بالسكريات الطبيعية، قوام زبدي فريد ومميز", "origin": "مستورد", "price": 11.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/ndLLS95/144-Custard-Apple-Kg-11.png" },
  { "id": 144, "category": "الفواكه", "name_ar": "تين محلي", "name_en": "Local Fig", "description": "تين وطني طازج بنفسجي غامق، ناعم وحلو جداً.", "features": "غني بالألياف، نكهة غنية، للأكل الطازج أو مع الجبن، موسمي فاخر", "origin": "إنتاج وطني (محلي)", "price": 23.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/QjJJTNwC/144-Local-Fig-Kg-23.png" },
  { "id": 145, "category": "الفواكه", "name_ar": "جريب فروت محلي", "name_en": "Local Grapefruit", "description": "جريب فروت وطني أصفر، نكهة حامضة مرة منعشة.", "features": "غني بفيتامين C، مثالي للإفطار الصحي والعصائر، محصول محلي طازج", "origin": "إنتاج وطني (محلي)", "price": 6.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/0y9XW4L9/145-Local-Grapefruit-Kg-6-5.png" },
  { "id": 146, "category": "الفواكه", "name_ar": "عنب أسود محلي", "name_en": "Local Black Grapes", "description": "عنب أسود وطني، حبات كبيرة حلوة جداً وقليلة البذور.", "features": "حلاوة عالية، محصول محلي فاخر، مثالي كوجبة خفيفة مغذية وصحية", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/HpB3L0b9/146-Local-Black-Grapes-Kg-13.png" },
  { "id": 147, "category": "الفواكه", "name_ar": "عنب أحمر محلي", "name_en": "Local Red Grapes", "description": "عنب أحمر وطني، حبات مقرمشة وحلوة خالية من البذور.", "features": "منعش، مثالي للسلطات والعصائر، حلاوة متوازنة، محصول طازج يومياً", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/MkXnFtGM/147-Local-Red-Grapes-Kg-13.png" },
  { "id": 148, "category": "الفواكه", "name_ar": "عنب أبيض محلي", "name_en": "Local White Grapes", "description": "عنب أبيض وطني ذهبي، حلاوة ونكهة منعشة.", "features": "مقرمش، محصول محلي طازج وممتاز، مثالي للأكل الطازج والمناسبات", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/kshDcLvx/148-Local-White-Grapes-Kg-13.png" },
  { "id": 149, "category": "الفواكه", "name_ar": "جوافة", "name_en": "Guava", "description": "جوافة طازجة خضراء مصفرة، نكهة عطرية مميزة.", "features": "غنية جداً بفيتامين C، تؤكل بقشرتها، مثالية للعصير الطبيعي المنعش", "origin": "إنتاج وطني (محلي)", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/RTjVgWtq/149-Guava-Kg-18.png" },
  { "id": 150, "category": "الفواكه", "name_ar": "كاكا", "name_en": "Persimmon", "description": "كاكا برتقالية زاهية، حلاوة عالية وقوام ناعم.", "features": "غنية بفيتامين A، نكهة حلوة مميزة، تؤكل طازجة أو تجفف بجودة عالية", "origin": "مستورد", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/kzNd609/150-Persimmon-Kg-18.png" },
  { "id": 151, "category": "الفواكه", "name_ar": "أفندي", "name_en": "Mandarin", "description": "أفندي (يوسفي) برتقالي، سهل التقشير وقليل البذور.", "features": "حلو المذاق، محبوب من الأطفال، غني بفيتامين C، للوجبات الخفيفة", "origin": "إنتاج وطني (محلي)", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/WNrP5fNp/151-Mandarin-Kg-9.png" },
  { "id": 152, "category": "الفواكه", "name_ar": "بابايا محلي", "name_en": "Local Papaya", "description": "بابايا وطنية كبيرة، لب برتقالي حلو ومنعش.", "features": "غنية بإنزيم البابين للهضم، طعم استوائي محلي ممتاز وعالي الجودة", "origin": "إنتاج وطني (محلي)", "price": 8.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/9HmLxRwV/152-Local-Papaya-Kg-8.png" },
  { "id": 153, "category": "الفواكه", "name_ar": "خوخ محلي", "name_en": "Local Peach", "description": "خوخ وطني أصفر محمر، حلاوة وعصارة ممتازة.", "features": "محصول محلي موسمي، طعم أصيل، مثالي للأكل اليومي، فاكهة فاخرة", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/cGJCkqH/153-Local-Peach-Kg-13.png" },
  { "id": 154, "category": "الفواكه", "name_ar": "أناناس بيبي", "name_en": "Baby Pineapple", "description": "أناناس بيبي صغير، حلاوة مركزة ونكهة قوية.", "features": "سهل التقطيع، مثالي لفرد واحد، طعم استوائي فاخر وفريد، حجم مثالي", "origin": "مستورد", "price": 25.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/99TQNSGL/154-Baby-Pineapple-Kg-25.png" },
  { "id": 155, "category": "الفواكه", "name_ar": "بطيخ طويل محلي", "name_en": "Long Watermelon", "description": "بطيخ طويل وطني، حلاوة عالية ولحم أحمر عصيري.", "features": "حجم عائلي كبير، حلو ومنعش، مثالي للجمعات العائلية في الصيف", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/sd3wDs0D/155-Long-Watermelon-Kg-3-5.png" },
  { "id": 156, "category": "الفواكه", "name_ar": "ليم أخضر", "name_en": "Green Lime", "description": "ليم أخضر (لايم) حامض جداً برائحة عطرية قوية.", "features": "منعش، للكوكتيلات والطبخ الآسيوي، نكهة مركزة، جودة توريد عالية", "origin": "مستورد", "price": 10.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/yrQQ5Mr/156-Green-Lime-Kg-10.png" },
  { "id": 157, "category": "الورقيات والأعشاب", "name_ar": "كزبرة", "name_en": "Coriander", "description": "كزبرة طازجة خضراء، أوراق ناعمة ورائحة عطرية قوية.", "features": "غنية بالفيتامينات، لا غنى عنها في المطبخ، تزرع محلياً لنضارة يومية", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/G4KZpJ8q/157-Coriander-PC-1-5.png" },
  { "id": 158, "category": "الورقيات والأعشاب", "name_ar": "بقدونس محلي", "name_en": "Parsley Local", "description": "بقدونس وطني طازج، أوراق خضراء داكنة ومقرمشة.", "features": "غني بالحديد، نكهة منعشة، للتبولة والسلطات والطبخ، قطف يومي", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/S4RKPy2T/158-Parsley-Local-PC-1-5.png" },
  { "id": 159, "category": "الورقيات والأعشاب", "name_ar": "جرجير", "name_en": "Rocket Local", "description": "جرجير محلي طازج، نكهة حادة مميزة ومنعشة.", "features": "غني بمضادات الأكسدة، مثالي مع السلطات والبيتزا، محصول يومي طازج", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/JFcvs60n/159-Rocket-Local-PC-1-5.png" },
  { "id": 160, "category": "الورقيات والأعشاب", "name_ar": "نعناع", "name_en": "Mint", "description": "نعناع أخضر طازج، أوراق عطرية منعشة جداً.", "features": "مهدئ طبيعي، مثالي للشاي واللبن، رائحة فواحة تضفي انتعاشاً فورياً", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/JFcvs60n/160-Mint-PC-1-5.png" },
  { "id": 161, "category": "الورقيات والأعشاب", "name_ar": "ملوخية", "name_en": "Molokhia", "description": "ملوخية خضراء طازجة، أوراق ناعمة وعالية الجودة.", "features": "غنية بالفيتامينات، قوام ممتاز بعد الطهي، قطف يومي لضمان الطعم", "origin": "إنتاج وطني (محلي)", "price": 6.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/39fqPkpC/161-Molokhia-Kg-6.png" },
  { "id": 162, "category": "الورقيات والأعشاب", "name_ar": "خس مدور محلي", "name_en": "Round Lettuce Local", "description": "خس مدور وطني، رأس متماسك وأوراق مقرمشة.", "features": "غني بالماء، قرمشة عالية، مثالي للسلطات والسندويشات، محصول طازج", "origin": "إنتاج وطني (محلي)", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/35fDPVLh/162-Round-Lettuce-Local-Kg-9.png" },
  { "id": 163, "category": "الورقيات والأعشاب", "name_ar": "سبانخ محلي", "name_en": "Local Spinach", "description": "سبانخ محلي طازج، أوراق خضراء داكنة غنية.", "features": "غنية بالحديد والفيتامينات، تطهى بسرعة، نكهة مميزة للأطباق الصحية", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/WpV5ZqTy/163-Local-Spinach-PC-1-5.png" },
  { "id": 164, "category": "الورقيات والأعشاب", "name_ar": "شبت", "name_en": "Dill", "description": "شبت طازج، أوراق خضراء ريشية ونكهة مميزة.", "features": "رائحة عطرية، مثالي مع السمك والمخللات، يضاف في آخر مراحل الطهي", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/4HM52Yc/164-Dill-PC-1-5.png" },
  { "id": 165, "category": "الورقيات والأعشاب", "name_ar": "كراث محلي", "name_en": "Local Leek", "description": "كراث محلي أخضر طازج، نكهة معتدلة ولذيذة.", "features": "يستخدم في الشوربات والطبخ، محصول يومي طازج، يضفي نكهة عميقة", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/8DRNVBxy/165-Local-Leek-PC-1-5.png" },
  { "id": 166, "category": "الورقيات والأعشاب", "name_ar": "خس طويل محلي", "name_en": "Romaine Lettuce Local", "description": "خس رومين طويل وطني، أوراق مقرمشة طويلة.", "features": "غني بالماء، قرمشة عالية، مثالي لسلطة السيزر والسندويشات الكبرى", "origin": "إنتاج وطني (محلي)", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/359FHvMW/166-Lettuce-Local-Kg-7.png" },
  { "id": 167, "category": "الورقيات والأعشاب", "name_ar": "رجلة", "name_en": "Purslane", "description": "رجلة (بقلة) طازجة، أوراق خضراء صغيرة سميكة.", "features": "نكهة حامضة قليلاً، غنية جداً بالأوميغا 3، فوائد صحية كبيرة ومنعشة", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/dJW48xmc/167-Pursaane-PC-1-5.png" },
  { "id": 168, "category": "الورقيات والأعشاب", "name_ar": "فجل أحمر", "name_en": "Red Radish", "description": "فجل أحمر طازج، حار ومنعش وقوي النكهة.", "features": "يفتح الشهية، مقرمش، يضاف للسلطات والمقبلات الشعبية، محصول طازج", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/Ndkyk1t3/168-Red-Radish-PC-1-5.png" },
  { "id": 169, "category": "الورقيات والأعشاب", "name_ar": "فجل أبيض", "name_en": "White Radish", "description": "فجل أبيض طويل، نكهة حارة قوية ومنعشة.", "features": "مقرمش، مثالي للأطباق الآسيوية والسلطات والمخللات، نضارة مضمونة", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/FZjpRVG/169-White-Radish-Kg-1-5.png" },
  { "id": 170, "category": "الورقيات والأعشاب", "name_ar": "كرفس محلي", "name_en": "Local Celery", "description": "كرفس وطني طازج، سيقان مقرمشة ونكهة مميزة.", "features": "غني بالألياف، مثالي للعصائر الصحية والسلطات، جودة محلية عالية", "origin": "إنتاج وطني (محلي)", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/nsbzkr9j/170-Local-Celery-Kg-18.png" },
  { "id": 171, "category": "الورقيات والأعشاب", "name_ar": "براعم ألفالفا", "name_en": "Alfalfa Sprouts", "description": "براعم ألفالفا طازجة وخفيفة، نكهة ناعمة ومنعشة.", "features": "غنية بالأنزيمات، تزيد القيمة الغذائية للسندويشات والسلطات الراقية", "origin": "مستورد", "price": 11.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "https://i.ibb.co/PzFGk7mp/171-AAlfalfa-Sprouts-PC-11.png" },
  { "id": 172, "category": "الورقيات والأعشاب", "name_ar": "أوراق خيزران", "name_en": "Bamboo Leaves", "description": "أوراق خيزران طازجة خضراء، للتغليف والطهي.", "features": "تضفي نكهة مميزة جداً عند الطهي بالبخار في المطبخ الآسيوي الفاخر", "origin": "مستورد", "price": 32.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Xfvw0Tw6/172-Bamboo-Leaves-Kg-32.png" },
  { "id": 173, "category": "الورقيات والأعشاب", "name_ar": "أوراق موز", "name_en": "Banana Leaves", "description": "أوراق موز كبيرة طازجة، تستخدم لتغليف الطعام.", "features": "تضفي رائحة ونكهة خفيفة ومميزة عند الشوي أو الطهي بالبخار", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/CKNBDPTJ/173-Banana-Leaves-Kg-35.png" },
  { "id": 174, "category": "الورقيات والأعشاب", "name_ar": "ريحان مستورد", "name_en": "Imported Basil", "description": "ريحان طازج عطر، نكهة حلوة قوية ومميزة جداً.", "features": "أساسي في المطبخ الإيطالي، مثالي للبيستو والسلطات الفاخرة، عطر فواح", "origin": "مستورد", "price": 58.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Q3vccT52/174-Imported-Basil-Kg-58.png" },
  { "id": 175, "category": "الورقيات والأعشاب", "name_ar": "شيكوري أحمر", "name_en": "Red Chicory", "description": "شيكوري أحمر (راديكيو) بنكهة مرة مميزة ومنعشة.", "features": "يضيف لوناً ونكهة للسلطات، مثالي للشوي، جودة توريد ممتازة وعالية", "origin": "مستورد", "price": 38.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/cXwQfgxp/175-Red-Chicory-Kg-38.png" },
  { "id": 176, "category": "الورقيات والأعشاب", "name_ar": "شيكوري أصفر", "name_en": "Yellow Chicory", "description": "شيكوري أصفر، نكهة مرة خفيفة وقوام مقرمش.", "features": "مثالي للسلطات الفاخرة، يضيف رقياً وتنوعاً للأطباق العالمية الراقية", "origin": "مستورد", "price": 38.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/fVqby3m2/176-Yellow-Chicory-Kg-38.png" },
  { "id": 177, "category": "الورقيات والأعشاب", "name_ar": "ثوم معمر", "name_en": "Chives", "description": "ثوم معمر طازج، أعواد خضراء بنكهة بصل خفيفة.", "features": "يستخدم للتزيين وإضافة نكهة راقية للسلطات والبطاطس والشوربات", "origin": "مستورد", "price": 70.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/C5M8y2f6/177-Chives-Kg-70.png" },
  { "id": 178, "category": "الورقيات والأعشاب", "name_ar": "إنديف مستورد", "name_en": "Imported Endive", "description": "إنديف بلجيكي أبيض مصفر، أوراق متماسكة مقرمشة.", "features": "نكهة مرة خفيفة، مثالي لتقديم المقبلات الراقية بأسلوب مبتكر", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/9HMSGHq8/178-Imported-Endive-Kg-35.png" },
  { "id": 179, "category": "الورقيات والأعشاب", "name_ar": "إنديف أصفر", "name_en": "Yellow Endive", "description": "إنديف أصفر بنفس الخصائص السابقة بلون أفتح.", "features": "نكهة فريدة، يضفي جمالية عالية للسلطات والمقبلات العالمية الراقية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/v4Jw9hbr/179-Yellow-Endive-Kg-35.png" },
  { "id": 180, "category": "الورقيات والأعشاب", "name_ar": "ريحان تاي أرجواني", "name_en": "Purple Thai Basil", "description": "ريحان تايلي أرجواني بنكهة حارة تشبه اليانسون.", "features": "أساسي في المطبخ التايلاندي، يتحمل درجات الحرارة العالية في الطهي", "origin": "مستورد", "price": 86.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/dwCf61bV/180-Purple-Thai-Basil-Kg-86.png" },
  { "id": 181, "category": "الورقيات والأعشاب", "name_ar": "روزماري مستورد", "name_en": "Imported Rosemary", "description": "روزماري طازج، أوراق إبرية عطرية ونكهة قوية.", "features": "مثالي لتتبيل اللحوم والدجاج والمخبوزات، رائحة عطرية فواحة جداً", "origin": "مستورد", "price": 58.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/xqNN8hQQ/181-Imported-Rosemary-Kg-58.png" },
  { "id": 182, "category": "الورقيات والأعشاب", "name_ar": "أعشاب الميرمية", "name_en": "Sage Herbs", "description": "مريمية طازجة بنكهة ترابية مميزة وعميقة.", "features": "تستخدم مع الدجاج واللحوم والوصفات الإيطالية، فوائد صحية معروفة", "origin": "مستورد", "price": 65.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/fYbFRt2R/182-Sage-Herbs-Kg-65.png" },
  { "id": 183, "category": "الورقيات والأعشاب", "name_ar": "أعشاب الطرخون", "name_en": "Tarragon Herbs", "description": "طرخون طازج بنكهة تشبه اليانسون ناعمة وراقية.", "features": "مثالي للصلصات الكريمية، الدجاج، والسلطات العالمية الراقية والفاخرة", "origin": "مستورد", "price": 88.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/jkwgpwC0/188-Tarragon-Herbs-Kg-88.png" },
  { "id": 184, "category": "الورقيات والأعشاب", "name_ar": "كيل هولندا", "name_en": "Kale (Holland)", "description": "كيل هولندي طازج، أوراق خضراء داكنة مجعدة.", "features": "سوبر فود، غني بالعناصر الغذائية، للسلطات والعصائر ورقائق الكيل", "origin": "هولندا", "price": 32.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/QvtD9wxw/184-Kale-Holland-Kg-32.png" },
  { "id": 185, "category": "الورقيات والأعشاب", "name_ar": "كراث (Leeks)", "name_en": "Leeks (Imported)", "description": "كراث مستورد بنكهة بصل معتدلة وراقية.", "features": "سيقان طويلة بيضاء وخضراء، مثالي للشوربات واليخنات والطبخ البطيء", "origin": "مستورد", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/rKyrPBm5/185-Leeks-Imported-Kg-18.png" },
  { "id": 186, "category": "الورقيات والأعشاب", "name_ar": "ليمون غراس", "name_en": "Lemon Grass", "description": "عشبة الليمون العطرية بنكهة ليمون منعشة جداً.", "features": "أساسي في المطبخ التايلاندي، يستخدم للشاي والطهي والصلصات الاستوائية", "origin": "مستورد", "price": 33.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/5xcRfPDW/186-Lemon-Grass-Kg-33.png" },
  { "id": 187, "category": "الورقيات والأعشاب", "name_ar": "ورق ليمون", "name_en": "Lemon Leaves", "description": "أوراق الليمون الطازجة، عطرية وفواحة جداً.", "features": "تستخدم لتغليف الطعام، إضافة نكهة للشاي، أو في الطبخ العطري", "origin": "مستورد", "price": 43.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/ccxWfh0G/187-Lemon-Leaves-Kg-43.png" },
  { "id": 188, "category": "الورقيات والأعشاب", "name_ar": "خس بوسطن", "name_en": "Boston Lettuce", "description": "خس بوسطن برأس ناعم وأوراق زبدية طرية.", "features": "نكهة خفيفة، مثالي للسلطات العالمية الفاخرة وتزيين الأطباق الراقية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/Z1k1vd51/188-Boston-Lettuce-Kg-35.png" },
  { "id": 189, "category": "الورقيات والأعشاب", "name_ar": "خس فريس أخضر", "name_en": "Green Frisee Lettuce", "description": "خس فريس أخضر مجعد، نكهة مرة خفيفة ومنعشة.", "features": "يضيف قرمشة وشكلاً رائعاً للسلطات، جودة توريد عالية للمطاعم الكبرى", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/pr098r7Z/189-Green-Frisee-Lettuce-Kg-35.png" },
  { "id": 190, "category": "الورقيات والأعشاب", "name_ar": "خس فريس أصفر", "name_en": "Yellow Frisee Lettuce", "description": "خس فريس أصفر مشابه للنوع السابق بلون ذهبي فاتح.", "features": "مثالي للسلطات المختلطة، يضيف تنوعاً بصرياً ونكهة مميزة للأطباق", "origin": "مستورد", "price": 48.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/1yByYj1/190-Yellow-Frisee-Lettuce-Kg-48.png" },
  { "id": 191, "category": "الورقيات والأعشاب", "name_ar": "خس راديكيو", "name_en": "Radicchio Lettuce", "description": "راديكيو أحمر برأس صلب ونكهة مرة مميزة.", "features": "أوراق حمراء بعروق بيضاء، مثالي للشوي والسلطات العالمية المبتكرة", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/DDvTs5DF/191-Radicchio-Lettuce-Kg-35.png" },
  { "id": 192, "category": "الورقيات والأعشاب", "name_ar": "خس بيبي جيم", "name_en": "Baby Gem Lettuce", "description": "خس بيبي جيم صغير الحجم ومقرمش جداً وحلو.", "features": "حجم مثالي لفرد واحد، أساسي لسلطة السيزر الفاخرة، قرمشة عالية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/kghpqW0q/192-Baby-Gem-Lettuce-Kg-35.png" },
  { "id": 193, "category": "الورقيات والأعشاب", "name_ar": "بوك تشوي", "name_en": "Bok Choy", "description": "بوك تشوي (كرنب صيني) طازج بنكهة خفيفة ومنعشة.", "features": "سيقان بيضاء وأوراق خضراء، أساسي في الطبخ الآسيوي، يطهى سريعاً", "origin": "مستورد", "price": 23.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/zTgz2z5G/193-Bok-Choy-Kg-23.png" },
  { "id": 194, "category": "الورقيات والأعشاب", "name_ar": "خس لولو بيوندي", "name_en": "Lollo Bionda Lettuce", "description": "خس لولو بيوندي بأوراق مجعدة خضراء فاتحة.", "features": "مقرمش ومنعش، يضيف شكلاً جمالياً وحجماً للسلطات، محصول طازج فاخر", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/tpGXLhnj/194-Lollo-Bionda-Lettuce-Kg-35.png" },
  { "id": 195, "category": "الورقيات والأعشاب", "name_ar": "خس لولو روسو", "name_en": "Lollo Rosso Lettuce", "description": "خس لولو روسو بأوراق مجعدة حمراء الأطراف.", "features": "نكهة خفيفة، مثالي لإضفاء اللون للسلطات وتزيين أطباق التقديم الراقية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/7NLPvQPD/195-Lollo-Rosso-Lettuce-Kg-35.png" },
  { "id": 196, "category": "الورقيات والأعشاب", "name_ar": "خس أوراق البلوط", "name_en": "Oak Leaf Lettuce", "description": "خس بأوراق تشبه أوراق البلوط، نكهة حلوة معتدلة.", "features": "ناعم ولذيذ، يتوفر باللونين الأخضر والأحمر، يضيف تنوعاً للسلطات", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/S7MBpKLj/196-Oak-Leaf-Lettuce-Kg-35.png" },
  { "id": 197, "category": "الورقيات والأعشاب", "name_ar": "جرجير بيبي", "name_en": "Baby Rocket", "description": "جرجير بيبي صغير الأوراق، نكهة ناعمة وحادة بشكل متوازن.", "features": "مثالي للسلطات العالمية الراقية، جودة توريد متميزة للمطاعم الكبرى", "origin": "مستورد", "price": 65.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/FkGjmCby/197-Baby-Rocket-Kg-65.png" },
  { "id": 198, "category": "الورقيات والأعشاب", "name_ar": "خس رومان", "name_en": "Romaine Lettuce", "description": "خس رومين مستورد، طويل ومقرمش جداً.", "features": "جودة عالية، مثالي لسلطة السيزر والجمعات، قوام متماسك ومنعش", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "15Er7Yg0eXfsyFHlM5komcGxHgsZPednq" },
  { "id": 199, "category": "الورقيات والأعشاب", "name_ar": "ورق لايم كافير", "name_en": "Kaffir Lime Leaves", "description": "أوراق لايم كافير عطرية جداً، نكهة ليمون قوية.", "features": "أساسية في المطبخ التايلاندي، تضفي نكهة ليمون عميقة وعطرية فواحة", "origin": "مستورد", "price": 48.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/RGShtxVq/199-Kaffir-Lime-Leaves-Kg-48.png" },
  { "id": 200, "category": "الورقيات والأعشاب", "name_ar": "أعشاب مايكرو", "name_en": "Micro Herbs", "description": "مجموعة أعشاب مايكرو صغيرة بنكهة مركزة.", "features": "مثالية لتزيين الأطباق الفاخرة، جودة فندقية، نكهات متنوعة وقوية", "origin": "مستورد", "price": 75.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/ycRy3NQh/200-Micro-Herbs-Kg-75.png" },
  { "id": 201, "category": "الورقيات والأعشاب", "name_ar": "أوريغانو طازج", "name_en": "Fresh Oregano", "description": "أوريغانو طازج، أوراق خضراء صغيرة ونكهة قوية.", "features": "مثالي للبيتزا والصلصات الإيطالية، رائحة عطرية فواحة عند الطهي", "origin": "مستورد", "price": 68.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/svHBLwr9/201-Fresh-Oregano-Kg-68.png" },
  { "id": 202, "category": "الورقيات والأعشاب", "name_ar": "بقدونس فرنسي", "name_en": "French Parsley", "description": "بقدونس فرنسي مسطح الأوراق، نكهة أقوى من العادي.", "features": "مثالي للطبخ الفرنسي، نكهة مركزة وعطرية، يستخدم في تتبيل اللحوم", "origin": "مستورد", "price": 28.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/G4Tm1jMx/202-French-Parsley-Kg-28.png" },
  { "id": 203, "category": "الورقيات والأعشاب", "name_ar": "بقدونس مجعد", "name_en": "Curly Parsley", "description": "بقدونس مجعد الأوراق، يستخدم غالباً للتزيين.", "features": "يحتفظ بمظهره الجذاب لفترة طويلة، يضيف لمسة جمالية رائعة للأطباق", "origin": "مستورد", "price": 29.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/dJskJWrN/203-Curly-Parsley-Kg-29.png" },
  { "id": 204, "category": "الورقيات والأعشاب", "name_ar": "ساكورا ميكس كريس", "name_en": "Sakura Mix Cress", "description": "ميكس من الكريس (الجرجير الصغير) بنكهات مختلفة.", "features": "مثالي للسلطات العالمية الفاخرة، نكهات مركزة ومتنوعة، شكل جذاب", "origin": "مستورد", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/BVyPcKQP/204-Sakura-Mix-Cress-Kg-80.png" },
  { "id": 205, "category": "الورقيات والأعشاب", "name_ar": "شيسو ميكس", "name_en": "Shiso Mix", "description": "ميكس من أوراق الشيسو اليابانية الفاخرة.", "features": "نكهة فريدة ومنعشة، مثالي للمطبخ الياباني (السوشي والساشيمي) الراقي", "origin": "مستورد", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/wrg9zMxP/205-Shiso-Mix-Kg-80.png" },
  { "id": 206, "category": "الورقيات والأعشاب", "name_ar": "براعم ساكورا ميكس", "name_en": "Sakura Mix Sprouts", "description": "براعم صغيرة من ميكس ساكورا، نكهة مركزة.", "features": "تضيف رقياً وقيمة غذائية للسندويشات والسلطات والمقبلات العالمية", "origin": "مستورد", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/d0yWcbcL/206-Sakura-Mix-Sprouts-Kg-80.png" },
  { "id": 207, "category": "الورقيات والأعشاب", "name_ar": "أوراق الزعتر", "name_en": "Thyme Leaves", "description": "زعتر طازج، أوراق صغيرة عطرية جداً.", "features": "مثالي لتتبيل اللحوم والدجاج والخضروات، رائحة عطرية تدوم طويلاً", "origin": "مستورد", "price": 58.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/3yKkP8b5/207-Thyme-Leaves-Kg-58.png" },
  { "id": 208, "category": "الورقيات والأعشاب", "name_ar": "زعتر بري طازج", "name_en": "Fresh Wild Thyme", "description": "زعتر بري طازج بنكهة أقوى من العادي.", "features": "رائحة فواحة جداً، مثالي للأطباق التقليدية والعالمية، جودة استثنائية", "origin": "مستورد", "price": 58.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/vCmgT14N/208-Fresh-Wild-Thyme-Kg-58.png" },
  { "id": 209, "category": "الورقيات والأعشاب", "name_ar": "راوند مستورد", "name_en": "Imported Rhubarb", "description": "راوند (ريباس) بساق حمراء وخضراء حامضة.", "features": "نكهة حامضة جداً ومميزة، يستخدم في الحلويات الفاخرة والمربيات", "origin": "مستورد", "price": 26.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/ycmJ8MTP/209-Imported-Rhubarb-Kg-26.png" },
  { "id": 210, "category": "الورقيات والأعشاب", "name_ar": "كرفس طازج (USA)", "name_en": "Fresh Celery (USA)", "description": "كرفس أمريكي طازج، سيقان طويلة مقرمشة.", "features": "جودة تصدير ممتازة، نكهة قوية، مثالي للعصائر الصحية والوجبات الخفيفة", "origin": "الولايات المتحدة الأمريكية", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/N2QRHD2y/210-Fresh-Celery-USA-Kg-18.png" },
  { "id": 211, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "يقطين القصيم", "name_en": "Qassim Pumpkin", "description": "يقطين القصيم الشهير، لون برتقالي وحلاوة عالية.", "features": "جودة فائقة، مثالي للحلويات والحساء، منتج محلي عريق من منطقة القصيم", "origin": "إنتاج وطني (القصيم)", "price": 5.5, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/jkGKJSTb/211-Qassim-Pumpkin-Kg-5-5.png" },
  { "id": 212, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "فلفل شقراء حار", "name_en": "Shaqra Chili", "description": "فلفل حار من شقراء، حرارة قوية ونكهة مميزة.", "features": "محصول محلي ممتاز، مثالي لإضافة نكهة حارة أصيلة للأطباق العربية", "origin": "إنتاج وطني (شقراء)", "price": 12.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/qYxQb52p/212-Shaqra-Chili-Kg-12.png" },
  { "id": 213, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "بصل القصيم", "name_en": "Qassim Onion", "description": "بصل أحمر وطني، نكهة قوية وقدرة تخزين.", "features": "جودة عالية، من أشهر أنواع البصل في المملكة، نكهة مركزة وممتازة", "origin": "إنتاج وطني (القصيم)", "price": 4.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/d4FZzq2y/Qassim-Onion-Kg-4.png" },
  { "id": 214, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "قرع أخضر طويل", "name_en": "Long Green Squash", "description": "قرع أخضر طويل (كوسا صيفي) نكهة خفيفة.", "features": "محصول طازج، مثالي للسلق والشوي واليخنات، قوام متماسك ولذيذ", "origin": "إنتاج وطني (محلي)", "price": 5.5, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/xStR8718/214-Long-Green-Squash-Kg-5-5.png" },
  { "id": 215, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "بصل أخضر القصيم", "name_en": "Qassim Spring Onion", "description": "بصل أخضر طازج، جزء أبيض لذيذ وأوراق خضراء.", "features": "نكهة معتدلة، مثالي للسلطات والتزيين، محصول طازج من مزارع القصيم", "origin": "إنتاج وطني (القصيم)", "price": 4.5, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/1ttvxJTg/215-Qassim-Spring-onion-Kg-4-5.jpg" },
  { "id": 216, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "كراث القصيم", "name_en": "Qassim Leek", "description": "كراث وطني طازج بنكهة مميزة.", "features": "محصول يومي، مثالي للشوربات والطبخ الشعبي، نكهة مركزة وطازجة", "origin": "إنتاج وطني (القصيم)", "price": 1.5, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/3nPjN8x/216-Qassim-Leek-PC-1-5.png" },
  { "id": 217, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "سكري مفتل", "name_en": "Sukari Muftal", "description": "تمر سكري مفتل فاخر، حبات ذهبية نصف جافة.", "features": "منتج فاخر للضيافة، حلاوة طبيعية عالية، عبوة 3 كغم، جودة قصيمية أصيلة", "origin": "إنتاج وطني (القصيم)", "price": 120.0, "price_unit": "ريال (للعبوة 3 كغم)", "image_url": "https://i.ibb.co/RkgcY2FB/217-120-Sukari-Muftal-3-Kg.png" },
  { "id": 218, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "مجدول القصيم", "name_en": "Qassim Majdool", "description": "تمر مجدول فاخر، حبات كبيرة طرية.", "features": "طعم كراميل لا يقاوم، من أرقى أنواع التمر، مثالية للهدايا والمناسبات", "origin": "إنتاج وطني (القصيم)", "price": 60.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/F4M1qQHm/118-Qassim-Majdool-Kg-60.png" },
  { "id": 219, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "صقعي القصيم", "name_en": "Qassim Sagai", "description": "تمر صقعي بلون أحمر ذهبي وحلاوة متوازنة.", "features": "قوام متماسك، مثالي للتخزين الطويل، يحتفظ بجودته ونكهته المميزة", "origin": "إنتاج وطني (القصيم)", "price": 55.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/sdvxvp3N/219-Qassim-Sagai-Kg-55.png" },
  { "id": 220, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "مبروم المدينة", "name_en": "Madinah Mabroom", "description": "تمر مبروم المدينة، حبات طويلة وطنية ناعمة.", "features": "نكهة غنية بالدبس، من تمور المدينة الفاخرة، قوام طري ومحبب للجميع", "origin": "إنتاج وطني (المدينة المنورة)", "price": 70.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/S4VLZ5YV/220-Madinah-Mabroom-Kg-70.png" },
  { "id": 221, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "صفاوي المدينة", "name_en": "Madinah Safawi", "description": "تمر صفاوي أسود اللون، متوسط الحجم وطري.", "features": "غني بالعناصر الغذائية، طعم لذيذ ومنعش، مثالي للإفطار اليومي الصحي", "origin": "إنتاج وطني (المدينة المنورة)", "price": 45.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/7dYCmP4L/221-Madinah-Safawi-Kg-45.png" },
  { "id": 222, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "عنبر المدينة", "name_en": "Madinah Anbar", "description": "تمر عنبر المدينة، كبير الحجم وأسود داكن.", "features": "من أندر وأغلى التمور، طعم استثنائي وفريد، قوام طري جداً وفاخر", "origin": "إنتاج وطني (المدينة المنورة)", "price": 90.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/sJVby2CB/222-Madinah-Amber-Kg-90.png" },
  { "id": 223, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "عجوة ملكي", "name_en": "Royal Ajwa", "description": "تمر عجوة ملكي فاخر، وطني ناعم ومبارك.", "features": "فوائد صحية عظيمة، تمور نبوية فاخرة، مثالية للهدايا بأعلى المعايير", "origin": "إنتاج وطني (المدينة المنورة)", "price": 80.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/PsX695RX/223-Royal-Ajwa-Kg-80.png" },
  { "id": 224, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "رطب سكري", "name_en": "Sukari Rutab", "description": "رطب سكري طازج طري جداً وحلو.", "features": "مرحلة الرطوبة الطازجة، طعم لا يقاوم، محصول موسمي يعبأ بعناية فائقة", "origin": "إنتاج وطني", "price": 45.0, "price_unit": "ريال (للعبوة - Ctn)", "image_url": "https://i.ibb.co/DP8JW9yC/224-Sukari-Rutab-Ctn-45.png" },
  { "id": 225, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "سلة الفواكه", "name_en": "Fruit Basket (S)", "description": "سلة فواكه مشكلة صغيرة بتنسيق جميل.", "features": "تشكيلة موسمية من أفضل الفواكه الطازجة، مثالية للهدايا والمناسبات", "origin": "تشكيلة متنوعة", "price": 50.0, "price_unit": "ريال (للسلة)", "image_url": "https://i.ibb.co/qLTW9G0n/225-S-50-Fruit-Basket.png" },
  { "id": 226, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "صندوق الخضار", "name_en": "Vegetable Box (M)", "description": "صندوق خضار متوسط متنوع ومختار.", "features": "تشكيلة خضروات طازجة مختارة بعناية، مثالي للعائلات، جودة توريد عالية", "origin": "تشكيلة محلية ومستوردة", "price": 75.0, "price_unit": "ريال (للصندوق)", "image_url": "https://i.ibb.co/LzX3fdWG/226-Vegetable-Box-M-M-75.png" },
  { "id": 227, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "سلة الورقيات", "name_en": "Leafy Greens Basket L", "description": "سلة كبيرة من الورقيات الطازجة والوطنية المنوعة", "features": "خس، جرجير، نعناع، كزبرة وأكثر، مثالية لعشاق السلطات الصحية يومياً", "origin": "إنتاج وطني (محلي)", "price": 30.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/LLK0w5T/223-Leafy-Greens-Basket-L-30.png" },
  { "id": 228, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "بيض الغربية", "name_en": "Gharbia Eggs Box", "description": "بيض بلدي طازج من الغربية عالي الجودة.", "features": "صفار ذهبي غني، مثالي للطهي، يعبأ في كرتون خاص لضمان السلامة", "origin": "إنتاج وطني (الغربية)", "price": 185.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/fz3nX6dg/228-Gharbia-Eggs-Box-185.png" },
  { "id": 229, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "زهور صالحة للأكل", "name_en": "Edible Flowers", "description": "مجموعة من الزهور الطازجة الصالحة للأكل.", "features": "ألوان زاهية، مثالية لتزيين الحلويات والسلطات الفاخرة، لمسة فنية راقية", "origin": "مستورد", "price": 170.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/W4XSf2sL/229-Edible-Flowers-Kg-170.png" },
  { "id": 230, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "جوز الهند", "name_en": "Coconut", "description": "جوز هند طازج بقشرة بنية وماء لذيذ.", "features": "يمكن شرب مائه وأكل لحمه الأبيض، مثالي للوصفات الاستوائية المنعشة", "origin": "مستورد", "price": 8.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/XkrP8LDV/230-Coconut-PC-8.png" },
  { "id": 231, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "قصب سكر", "name_en": "Sugar Cane", "description": "أعواد قصب سكر طازجة وعصيرية.", "features": "مصدر طبيعي للسكر، يمكن مضغه لاستخراج العصير الحلو المنعش جداً", "origin": "مستورد", "price": 20.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/7dHCpPp8/231-Sugar-Cane-Kg-20.png" },
  { "id": 232, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "فطر ترمبيت أسود", "name_en": "Black Trumpet Mushroom", "description": "فطر ترمبيت أسود فاخر ونادر جداً.", "features": "نكهة ترابية قوية، من أفخر أنواع الفطر البري، يتطلب معالجة خاصة", "origin": "مستورد", "price": 85.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/jk7ndFCg/232-Black-Trumpet-Mushroom-Kg.png" },
  { "id": 233, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "فطر بلوفوت", "name_en": "Bluefoot Mushroom", "description": "فطر بلوفوت بقاعدة زرقاء نادرة.", "features": "نكهة جوزية خفيفة، منتج موسمي نادر، مثالي للشوي والصلصات العالمية", "origin": "مستورد", "price": 95.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/9mGgSXnX/233-Bluefoot-Mushroom.png" },
  { "id": 234, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "فطر جيرول صغير", "name_en": "Small Girolle Mushroom", "description": "فطر جيرول (شانتيريل) أصفر ذهبي.", "features": "نكهة فاكهية مميزة، من أشهر أنواع الفطر البري، مثالي للريزوتو الفاخر", "origin": "مستورد", "price": 110.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/h11LYVyz/234-Small-Girolle-Mushroom-Kg.png" },
  { "id": 235, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "توت أسود طائفي", "name_en": "Taifi Blackberries", "description": "توت أسود طائفي طازج وحلو جداً.", "features": "إنتاج محلي محدود، طعم استثنائي، من مزارع الطائف العريقة، معالجة خاصة", "origin": "إنتاج وطني (الطائف)", "price": 35.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/qYDp8MwH/235-Taifi-Blackberries-Kg.png" },
  { "id": 236, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "فطر شميجي بني تايلندي", "name_en": "Brown shmegey Mushroom", "description": "فطر شميجي بني تايلندي طازج، يتميز بنكهة جوزية وقوام متماسك.", "features": "غني بالفيتامينات، مثالي للقلي السريع والشوربات، جودة توريد عالية", "origin": "تايلاند", "price": 45.0, "price_unit": "ريال (عبوة 5 كجم)", "image_url": "https://i.ibb.co/F41772NQ/Brown-shmegey-Mushroom.jpg" },
  { "id": 237, "category": "خضروات", "name_ar": "باذنجان طويل", "name_en": "Eggplant Long", "description": "باذنجان طويل طازج عالي الجودة.", "features": "مثالي للمحاشي والقلي، قوام متماسك وطعم غني، محصول محلي طازج", "origin": "إنتاج وطني", "price": 5.0, "price_unit": "ريال للكيلو", "image_url": "https://i.ibb.co/KjDydmBZ/Eggplant-Long-Kg5.png" }
];

const generateFullCatalog = (): Product[] => {
  return rawJsonData.map(item => {
    const mainImage = fixDriveLink(item.image_url);
    const unitAr = item.price_unit;
    const isKg = unitAr.includes('كيلو') || unitAr.includes('Kg');
    
    // Weight logic enhancement
    let displayUnitAr = unitAr;
    if (isKg) displayUnitAr = "كيلو جرام (متاح بدءاً من 500 جرام)";
    else if (unitAr.includes('حزمة')) displayUnitAr = "حزمة طازجة (ربطة)";
    else if (unitAr.includes('عبوة')) displayUnitAr = "عبوة باكت (مغلفة)";

    return {
      id: item.id,
      name_ar: item.name_ar,
      name_en: item.name_en || item.name_ar,
      category: mapCategory(item.category, item.name_ar),
      price: item.price,
      price_500g: isKg ? parseFloat((item.price / 2).toFixed(2)) : undefined,
      price_1kg: isKg ? item.price : undefined,
      image: mainImage,
      gallery: [
        mainImage,
        `https://picsum.photos/seed/${item.id + 100}/800/800`,
        `https://picsum.photos/seed/${item.id + 200}/800/800`
      ],
      unit_ar: displayUnitAr,
      unit_en: mapUnitArToEn(item.price_unit),
      description_ar: item.description,
      description_en: (item.name_en || item.name_ar) + " - Premium Institutional Quality.",
      features_ar: item.features,
      features_en: "High-grade fresh produce, carefully selected for professional use. Guaranteed freshness and quality standards.",
      nutritional_value_ar: "غني بالفيتامينات والمعادن الأساسية للجسم، خالي من المواد المعدلة وراثياً.",
      nutritional_value_en: "Rich in essential vitamins and minerals, GMO-free, fresh farm produce.",
      origin_ar: item.origin,
      origin_en: item.origin.includes('وطني') ? "Saudi Local (National Production)" : "International Import",
      stock_quantity: 1000,
      min_threshold: 50
    };
  });
};

export const mockProducts: Product[] = generateFullCatalog();